// mgmt/frontend-svelte/src/lib/views/Committee.svelte
<script lang="ts">
  // Ported from React views/Committee.jsx — list committee members for a year,
  // add/edit/delete (COMMITEE MEMBERS sheet), same cache invalidation.
  import { api } from '$lib/api';
  import { createViewData, type ViewData } from '$lib/viewData';
  import { invalidate } from '$lib/cache';
  import Modal from '$lib/components/Modal.svelte';
  import RowActions from '$lib/components/RowActions.svelte';
  import TransliterateInput from '$lib/components/TransliterateInput.svelte';
  import { canAddView } from '$lib/permissions';

  interface Props {
    year: string;
    users: any[];
    role: string;
    editable: boolean;
  }
  let { year, users, role, editable }: Props = $props();

  const VIEW_ROLE_SUGGESTIONS = ['President', 'Vice President', 'Secretary', 'Treasurer', 'Member'];
  const BLANK = { Name: '', 'View Role': '', 'View Role (Hindi)': '' };

  // Re-create the year-scoped view whenever `year` changes (matches useViewData deps).
  let view = $state<ViewData<any[]>>(createViewData(`committee:${year}`, () => api.getCommittee(year)));
  let lastYear = year;
  $effect(() => {
    if (year !== lastYear) {
      lastYear = year;
      view = createViewData(`committee:${year}`, () => api.getCommittee(year));
    }
  });
  let vs = $state({ data: undefined as any, list: [] as any[], loading: true, error: '' });
  $effect(() => {
    const unsub = view.subscribe((v) => (vs = v as any));
    return unsub;
  });

  let showAdd = $state(false);
  let form = $state<any>({ ...BLANK });
  let saving = $state(false);
  let editing = $state<any>(null);

  let userMap = $derived.by(() => {
    const m: Record<string, any> = {};
    (users || []).forEach((u) => (m[u.ID] = u));
    return m;
  });

  function closeModal() {
    showAdd = false;
    editing = null;
    form = { ...BLANK };
  }
  function openEdit(r: any) {
    editing = r;
    form = { Name: r.Name, 'View Role': r['View Role'] || '', 'View Role (Hindi)': r['View Role (Hindi)'] || '' };
    showAdd = true;
  }

  async function submit(e: Event) {
    e.preventDefault();
    if (!form.Name) { alert('Fill all fields'); return; }
    saving = true;
    try {
      if (editing) {
        await api.updateRecord('COMMITEE MEMBERS', editing.__rowIndex, {
          Year: editing.Year,
          Name: form.Name,
          'View Role': form['View Role'],
          'View Role (Hindi)': form['View Role (Hindi)'],
          'Created By': editing['Created By']
        });
      } else {
        await api.saveRecord('COMMITEE MEMBERS', { Year: year === 'All' ? new Date().getFullYear() : year, ...form });
      }
      invalidate('committee:');
      closeModal();
      view.refresh();
    } catch (err) {
      alert((err as Error).message);
    } finally {
      saving = false;
    }
  }

  async function remove(r: any) {
    if (!confirm(`Delete ${r.Name}'s committee membership?`)) return;
    try {
      await api.deleteRecord('COMMITEE MEMBERS', r.__rowIndex);
      invalidate('committee:');
      view.refresh();
    } catch (err) {
      alert((err as Error).message);
    }
  }
</script>

{#if vs.loading}
  <div class="inline-spinner">Loading committee...</div>
{:else if vs.error}
  <div class="error-banner">{vs.error}</div>
{:else}
  <h2 style="margin-bottom:15px;">Active Committee</h2>
  {#if !vs.data || vs.data.length === 0}
    <div class="glass-card" style="text-align:center; padding:20px;">No committee on record.</div>
  {/if}
  {#each vs.data || [] as r, i (r.__rowIndex ?? i)}
    {@const u = userMap[r.Name] || { Name: r.Name ? `${r.Name} (not in Users)` : 'Unknown', Mobile: 'N/A', Village: 'N/A' }}
    <div class="glass-card" style="padding:15px; margin-bottom:12px; display:flex; gap:15px; align-items:center;">
      <div style="width:50px; height:50px; border-radius:50%; background:var(--saffron-light); color:var(--primary-saffron); display:flex; align-items:center; justify-content:center; font-weight:bold; flex-shrink:0;">
        {(u.Name?.[0] || '?').toUpperCase()}
      </div>
      <div style="flex-grow:1;">
        <div style="display:flex; justify-content:space-between;">
          <strong>{u.Name}</strong>
          <span class="badge" style="background:#f3f4f6; color:#374151;">{r.Year}</span>
        </div>
        {#if r['View Role']}
          <div class="role-select-badge" style="display:inline-block; margin-bottom:4px;">
            {r['View Role']}{r['View Role (Hindi)'] ? ` (${r['View Role (Hindi)']})` : ''}
          </div>
        {/if}
        <div style="font-size:0.8rem; color:var(--text-muted);">{u.Mobile || 'N/A'} | {u.Village || 'N/A'}</div>
      </div>
      <RowActions {role} disabled={!editable} onEdit={() => openEdit(r)} onDelete={() => remove(r)} />
    </div>
  {/each}

  {#if editable && canAddView(role, 'committee')}
    <button class="fab" onclick={() => (showAdd = true)}><span class="material-icons-round">add</span></button>
  {/if}

  <Modal open={showAdd} onClose={closeModal}>
    <h3 style="margin-bottom:15px;">{editing ? 'Edit Committee Member' : 'Add Committee Member'}</h3>
    <form onsubmit={submit}>
      <div class="form-group">
        <label>User</label>
        <select bind:value={form.Name}>
          <option value="" disabled>-- Select --</option>
          {#each users || [] as u (u.ID)}
            <option value={u.ID}>{u.Name}</option>
          {/each}
        </select>
      </div>
      <TransliterateInput
        label="View Role (public designation — shown to everyone)"
        placeholder="e.g. President, Secretary, Member"
        listId="view-role-suggestions"
        value={{ en: form['View Role'], hi: form['View Role (Hindi)'] }}
        onChange={({ en, hi }) => (form = { ...form, 'View Role': en, 'View Role (Hindi)': hi })}
      />
      <datalist id="view-role-suggestions">
        {#each VIEW_ROLE_SUGGESTIONS as v}<option value={v}></option>{/each}
      </datalist>
      <p style="font-size:0.75rem; color:var(--text-muted); margin-top:-8px; margin-bottom:12px;">
        Login (Role + Password) is now managed from the "Login Management" page.
      </p>
      <button class="btn-submit" disabled={saving}>{saving ? 'Saving...' : 'Save'}</button>
    </form>
  </Modal>
{/if}

// mgmt/frontend/src/views/Committee.jsx
import { useState, useMemo } from 'react';
import { api } from '../api.js';
import { useViewData } from '../useViewData.js';
import { invalidate } from '../cache.js';
import Modal from '../components/Modal.jsx';
import RowActions from '../components/RowActions.jsx';
import { canAddView } from '../permissions.js';
import TransliterateInput from '../components/TransliterateInput.jsx';

const VIEW_ROLE_SUGGESTIONS = ['President', 'Vice President', 'Secretary', 'Treasurer', 'Member'];
const BLANK = { Name: '', 'View Role': '', 'View Role (Hindi)': '' };

export default function Committee({ year, users, role, editable }) {
  const { data, loading, error, refresh } = useViewData(`committee:${year}`, () => api.getCommittee(year), [year]);
  const [showAdd, setShowAdd] = useState(false);
  const [form, setForm] = useState(BLANK);
  const [saving, setSaving] = useState(false);
  const [editing, setEditing] = useState(null);

  const userMap = useMemo(() => {
    const m = {};
    (users || []).forEach(u => { m[u.ID] = u; });
    return m;
  }, [users]);

  const closeModal = () => {
    setShowAdd(false);
    setEditing(null);
    setForm(BLANK);
  };

  const openEdit = (r) => {
    setEditing(r);
    setForm({ Name: r.Name, 'View Role': r['View Role'] || '', 'View Role (Hindi)': r['View Role (Hindi)'] || '' });
    setShowAdd(true);
  };

  const submit = async (e) => {
    e.preventDefault();
    if (!form.Name) return alert('Fill all fields');
    setSaving(true);
    try {
      if (editing) {
        await api.updateRecord('COMMITEE MEMBERS', editing.__rowIndex, { Year: editing.Year, Name: form.Name, 'View Role': form['View Role'], 'View Role (Hindi)': form['View Role (Hindi)'], 'Created By': editing['Created By'] });
      } else {
        await api.saveRecord('COMMITEE MEMBERS', { Year: year === 'All' ? new Date().getFullYear() : year, ...form });
      }
      invalidate('committee:');
      closeModal();
      refresh();
    } catch (err) {
      alert(err.message);
    } finally {
      setSaving(false);
    }
  };

  const remove = async (r) => {
    if (!confirm(`Delete ${r.Name}'s committee membership?`)) return;
    try {
      await api.deleteRecord('COMMITEE MEMBERS', r.__rowIndex);
      invalidate('committee:');
      refresh();
    } catch (err) {
      alert(err.message);
    }
  };

  if (loading) return <div className="inline-spinner">Loading committee...</div>;
  if (error) return <div className="error-banner">{error}</div>;

  return (
    <>
      <h2 style={{ marginBottom: 15 }}>Active Committee</h2>
      {(!data || data.length === 0) && <div className="glass-card" style={{ textAlign: 'center', padding: 20 }}>No committee on record.</div>}
      {(data || []).map((r, i) => {
        const u = userMap[r.Name] || { Name: r.Name ? `${r.Name} (not in Users)` : 'Unknown', Mobile: 'N/A', Village: 'N/A' };
        return (
          <div className="glass-card" style={{ padding: 15, marginBottom: 12, display: 'flex', gap: 15, alignItems: 'center' }} key={r.__rowIndex ?? i}>
            <div style={{ width: 50, height: 50, borderRadius: '50%', background: 'var(--saffron-light)', color: 'var(--primary-saffron)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold', flexShrink: 0 }}>
              {(u.Name?.[0] || '?').toUpperCase()}
            </div>
            <div style={{ flexGrow: 1 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <strong>{u.Name}</strong>
                <span className="badge" style={{ background: '#f3f4f6', color: '#374151' }}>{r.Year}</span>
              </div>
              {}
              {r['View Role'] && <div className="role-select-badge" style={{ display: 'inline-block', marginBottom: 4 }}>{r['View Role']}{r['View Role (Hindi)'] ? ` (${r['View Role (Hindi)']})` : ''}</div>}
              <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>{u.Mobile || 'N/A'} | {u.Village || 'N/A'}</div>
            </div>
            <RowActions role={role} disabled={!editable} onEdit={() => openEdit(r)} onDelete={() => remove(r)} />
          </div>
        );
      })}

      {editable && canAddView(role, 'committee') && (
        <button className="fab" onClick={() => setShowAdd(true)}><span className="material-icons-round">add</span></button>
      )}

      <Modal open={showAdd} onClose={closeModal}>
        <h3 style={{ marginBottom: 15 }}>{editing ? 'Edit Committee Member' : 'Add Committee Member'}</h3>
        <form onSubmit={submit}>
          <div className="form-group">
            <label>User</label>
            <select value={form.Name} onChange={e => setForm({ ...form, Name: e.target.value })}>
              <option value="" disabled>-- Select --</option>
              {(users || []).map(u => <option key={u.ID} value={u.ID}>{u.Name}</option>)}
            </select>
          </div>
          <TransliterateInput
            label="View Role (public designation — shown to everyone)"
            placeholder="e.g. President, Secretary, Member"
            listId="view-role-suggestions"
            value={{ en: form['View Role'], hi: form['View Role (Hindi)'] }}
            onChange={({ en, hi }) => setForm({ ...form, 'View Role': en, 'View Role (Hindi)': hi })}
          />
          <datalist id="view-role-suggestions">
            {VIEW_ROLE_SUGGESTIONS.map(v => <option key={v} value={v} />)}
          </datalist>
          <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: -8, marginBottom: 12 }}>
            Login (Role + Password) is now managed from the "Login Management" page.
          </p>
          <button className="btn-submit" disabled={saving}>{saving ? 'Saving...' : 'Save'}</button>
        </form>
      </Modal>
    </>
  );
}
