// mgmt/frontend/src/views/DownloadCenter.jsx
import { useState } from 'react';
import { api } from '../api.js';
import { fillDocxTemplateFromRow } from '../docxFill.js';
import { generateQrDataUrl, publicRecordUrl } from '../qrCode.js';
import { useDropdownList } from '../useDropdownList.js';

function DownloadItem({ item, onGenerated, canGenerate }) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');

  const generate = async () => {
    setBusy(true);
    setError('');
    try {
      const templateRow = await api.getDocxTemplateForDoc(item.docType, item.year).catch(() => null);
      if (!templateRow || (!templateRow.base64 && !templateRow.downloadUrl)) {
        setError('No .docx template exists for this year/type (upload one in the Document Templates tab).');
        return;
      }
      const qrCode = await generateQrDataUrl(publicRecordUrl(item.recordId)).catch(() => '');
      const filledBase64 = await fillDocxTemplateFromRow(templateRow, { ...item.placeholders, GENERATED_AT: new Date().toLocaleString('en-IN'), QR_CODE: qrCode });
      const fileName = `${item.fileNameHint}.docx`;
      const res = await api.convertDocxToPdf(item.docType, item.year, item.recordId, filledBase64, fileName);
      onGenerated(item.recordId, res.publicLink);
    } catch (err) {
      setError(err.message);
    } finally {
      setBusy(false);
    }
  };

  return (
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 8, padding: '10px 0', borderBottom: '1px solid #f0f0f0', flexWrap: 'wrap' }}>
      <div>
        <div style={{ fontSize: '0.9rem' }}>{item.label}</div>
        {error && <div style={{ fontSize: '0.75rem', color: 'var(--danger)' }}>{error}</div>}
      </div>
      {item.publicLink ? (
        <a href={item.publicLink} target="_blank" rel="noreferrer" className="btn-submit" style={{ width: 'auto', padding: '6px 14px', fontSize: '0.85rem', textDecoration: 'none', textAlign: 'center' }}>
          ⬇ Download
        </a>
      ) : canGenerate ? (
        <button className="btn-submit" style={{ width: 'auto', padding: '6px 14px', fontSize: '0.85rem', background: '#e5e7eb', color: '#111' }} onClick={generate} disabled={busy}>
          {busy ? 'Generating...' : 'Generate Now'}
        </button>
      ) : (
        <span className="badge" style={{ background: '#f3f4f6', color: 'var(--text-muted)' }}>Not Available</span>
      )}
    </div>
  );
}

function Section({ title, items, onGenerated, canGenerate }) {
  if (!items || items.length === 0) return null;
  return (
    <div className="glass-card" style={{ padding: 15, marginBottom: 15 }}>
      <strong>{title}</strong>
      <div style={{ marginTop: 8 }}>
        {items.map(item => <DownloadItem key={item.recordId} item={item} onGenerated={onGenerated} canGenerate={canGenerate} />)}
      </div>
    </div>
  );
}

export default function DownloadCenter({ role }) {
  const canGenerate = role === 'Superadmin';
  const { options: villages } = useDropdownList('Village');
  const [village, setVillage] = useState('');
  const [nameQuery, setNameQuery] = useState('');
  const [results, setResults] = useState(null);
  const [searching, setSearching] = useState(false);
  const [selected, setSelected] = useState(null);
  const [downloads, setDownloads] = useState(null);
  const [loadingDownloads, setLoadingDownloads] = useState(false);
  const [error, setError] = useState('');

  const search = async () => {
    if (!village) return alert('Please select a village first');
    setSearching(true);
    setError('');
    setSelected(null);
    setDownloads(null);
    try {
      const res = await api.searchUsersByVillageAndName(village, nameQuery);
      setResults(res);
    } catch (err) {
      setError(err.message);
    } finally {
      setSearching(false);
    }
  };

  const selectUser = async (u) => {
    setSelected(u);
    setLoadingDownloads(true);
    setError('');
    try {
      const res = await api.getPersonDownloads(u.ID);
      setDownloads(res);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoadingDownloads(false);
    }
  };

  const markGenerated = (recordId, publicLink) => {
    setDownloads(d => {
      if (!d) return d;
      const patch = (arr) => arr.map(item => item.recordId === recordId ? { ...item, publicLink } : item);
      return { ...d, collections: patch(d.collections), loanerItems: patch(d.loanerItems), guarantorItems: patch(d.guarantorItems) };
    });
  };

  return (
    <>
      <h2 style={{ marginBottom: 15 }}>Download Center</h2>
      {error && <div className="error-banner">{error}</div>}

      <div className="glass-card" style={{ padding: 15, marginBottom: 15 }}>
        <div className="form-group">
          <label>Village</label>
          <select value={village} onChange={e => { setVillage(e.target.value); setResults(null); setSelected(null); setDownloads(null); }}>
            <option value="">-- Select Village --</option>
            {villages.map(v => <option key={v['English Value']} value={v['English Value']}>{v['English Value']}</option>)}
          </select>
        </div>
        <div className="form-group">
          <label>Name / Mobile / ID</label>
          <input value={nameQuery} onChange={e => setNameQuery(e.target.value)} placeholder="Search..." disabled={!village} />
        </div>
        <button className="btn-submit" onClick={search} disabled={searching || !village}>{searching ? 'Searching...' : 'Search'}</button>
      </div>

      {results && !selected && (
        <div className="glass-card" style={{ padding: 15, marginBottom: 15 }}>
          {results.length === 0 && <div style={{ textAlign: 'center', padding: 10 }}>No matches found.</div>}
          {results.map(u => (
            <div
              key={u.ID}
              onClick={() => selectUser(u)}
              style={{ padding: '10px 0', borderBottom: '1px solid #f0f0f0', cursor: 'pointer' }}
            >
              <strong>{u.Name}</strong>
              <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>{u.Village} {u.Mobile ? `| ${u.Mobile}` : ''}</div>
            </div>
          ))}
        </div>
      )}

      {selected && (
        <>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 }}>
            <strong>{selected.Name} ({selected.Village})</strong>
            <button type="button" className="btn-submit" style={{ width: 'auto', background: '#e5e7eb', color: '#111' }} onClick={() => { setSelected(null); setDownloads(null); }}>
              ← Back
            </button>
          </div>

          {loadingDownloads && <div className="inline-spinner">Loading...</div>}

          {downloads && (
            <>
              <Section title="Receipts / Certificates / Material" items={downloads.collections} onGenerated={markGenerated} canGenerate={canGenerate} />
              <Section title="Loan Consent (Loaner)" items={downloads.loanerItems} onGenerated={markGenerated} canGenerate={canGenerate} />
              <Section title="Loan Consent (Guarantor)" items={downloads.guarantorItems} onGenerated={markGenerated} canGenerate={canGenerate} />
              {downloads.collections.length === 0 && downloads.loanerItems.length === 0 && downloads.guarantorItems.length === 0 && (
                <div className="glass-card" style={{ textAlign: 'center', padding: 20 }}>No downloadable records available for this person.</div>
              )}
            </>
          )}
        </>
      )}
    </>
  );
}

// mgmt/frontend-svelte/src/lib/views/DownloadCenter.svelte
<script lang="ts">
  // Ported from React views/DownloadCenter.jsx — search a person by village +
  // name, list their downloadable docs (collections / loaner / guarantor) and
  // generate/download each. Section rendering inlined; item is DownloadItem.
  import { api } from '$lib/api';
  import { createDropdownList } from '$lib/dropdownList';
  import DownloadItem from '$lib/components/DownloadItem.svelte';

  interface Props {
    role: string;
  }
  let { role }: Props = $props();

  let canGenerate = $derived(role === 'Superadmin');

  const villageList = createDropdownList('Village');
  let villages = $state<any[]>([]);
  $effect(() => villageList.subscribe((s) => (villages = s.options)));

  let village = $state('');
  let nameQuery = $state('');
  let results = $state<any[] | null>(null);
  let searching = $state(false);
  let selected = $state<any>(null);
  let downloads = $state<any>(null);
  let loadingDownloads = $state(false);
  let error = $state('');

  async function search() {
    if (!village) { alert('Please select a village first'); return; }
    searching = true;
    error = '';
    selected = null;
    downloads = null;
    try {
      const res: any = await api.searchUsersByVillageAndName(village, nameQuery);
      results = res;
    } catch (err) {
      error = (err as Error).message;
    } finally {
      searching = false;
    }
  }

  async function selectUser(u: any) {
    selected = u;
    loadingDownloads = true;
    error = '';
    try {
      const res: any = await api.getPersonDownloads(u.ID);
      downloads = res;
    } catch (err) {
      error = (err as Error).message;
    } finally {
      loadingDownloads = false;
    }
  }

  function markGenerated(recordId: string, publicLink: string) {
    if (!downloads) return;
    const patch = (arr: any[]) => arr.map((item) => (item.recordId === recordId ? { ...item, publicLink } : item));
    downloads = {
      ...downloads,
      collections: patch(downloads.collections),
      loanerItems: patch(downloads.loanerItems),
      guarantorItems: patch(downloads.guarantorItems)
    };
  }
</script>

<h2 style="margin-bottom:15px;">Download Center</h2>
{#if error}<div class="error-banner">{error}</div>{/if}

<div class="glass-card" style="padding:15px; margin-bottom:15px;">
  <div class="form-group">
    <label>Village</label>
    <select
      value={village}
      onchange={(e) => { village = (e.currentTarget as HTMLSelectElement).value; results = null; selected = null; downloads = null; }}
    >
      <option value="">-- Select Village --</option>
      {#each villages as v (v['English Value'])}
        <option value={v['English Value']}>{v['English Value']}</option>
      {/each}
    </select>
  </div>
  <div class="form-group">
    <label>Name / Mobile / ID</label>
    <input bind:value={nameQuery} placeholder="Search..." disabled={!village} />
  </div>
  <button class="btn-submit" onclick={search} disabled={searching || !village}>{searching ? 'Searching...' : 'Search'}</button>
</div>

{#if results && !selected}
  <div class="glass-card" style="padding:15px; margin-bottom:15px;">
    {#if results.length === 0}<div style="text-align:center; padding:10px;">No matches found.</div>{/if}
    {#each results as u (u.ID)}
      <!-- svelte-ignore a11y_click_events_have_key_events -->
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <div onclick={() => selectUser(u)} style="padding:10px 0; border-bottom:1px solid #f0f0f0; cursor:pointer;">
        <strong>{u.Name}</strong>
        <div style="font-size:0.8rem; color:var(--text-muted);">{u.Village} {u.Mobile ? `| ${u.Mobile}` : ''}</div>
      </div>
    {/each}
  </div>
{/if}

{#if selected}
  <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:10px;">
    <strong>{selected.Name} ({selected.Village})</strong>
    <button type="button" class="btn-submit" style="width:auto; background:#e5e7eb; color:#111;" onclick={() => { selected = null; downloads = null; }}>
      ← Back
    </button>
  </div>

  {#if loadingDownloads}<div class="inline-spinner">Loading...</div>{/if}

  {#if downloads}
    {#if downloads.collections && downloads.collections.length > 0}
      <div class="glass-card" style="padding:15px; margin-bottom:15px;">
        <strong>Receipts / Certificates / Material</strong>
        <div style="margin-top:8px;">
          {#each downloads.collections as item (item.recordId)}
            <DownloadItem {item} onGenerated={markGenerated} {canGenerate} />
          {/each}
        </div>
      </div>
    {/if}
    {#if downloads.loanerItems && downloads.loanerItems.length > 0}
      <div class="glass-card" style="padding:15px; margin-bottom:15px;">
        <strong>Loan Consent (Loaner)</strong>
        <div style="margin-top:8px;">
          {#each downloads.loanerItems as item (item.recordId)}
            <DownloadItem {item} onGenerated={markGenerated} {canGenerate} />
          {/each}
        </div>
      </div>
    {/if}
    {#if downloads.guarantorItems && downloads.guarantorItems.length > 0}
      <div class="glass-card" style="padding:15px; margin-bottom:15px;">
        <strong>Loan Consent (Guarantor)</strong>
        <div style="margin-top:8px;">
          {#each downloads.guarantorItems as item (item.recordId)}
            <DownloadItem {item} onGenerated={markGenerated} {canGenerate} />
          {/each}
        </div>
      </div>
    {/if}
    {#if downloads.collections.length === 0 && downloads.loanerItems.length === 0 && downloads.guarantorItems.length === 0}
      <div class="glass-card" style="text-align:center; padding:20px;">No downloadable records available for this person.</div>
    {/if}
  {/if}
{/if}
