// mgmt/frontend/src/views/EmailOfficial.jsx
import { useEffect, useState, useCallback } from 'react';
import DOMPurify from 'dompurify';
import { api } from '../api.js';
import { usePolling } from '../usePolling.js';
import Modal from '../components/Modal.jsx';


function fmtDate(s) {
  if (!s) return '';
  const d = new Date(s);
  return isNaN(d) ? s : d.toLocaleString();
}

function BodyView({ html, text }) {
  if (html && html.trim()) {
    const clean = DOMPurify.sanitize(html, { USE_PROFILES: { html: true } });
    return <div style={{ fontSize: '0.9rem', lineHeight: 1.5 }} dangerouslySetInnerHTML={{ __html: clean }} />;
  }
  if (text && text.trim()) {
    return <div style={{ fontSize: '0.9rem', lineHeight: 1.5, whiteSpace: 'pre-wrap' }}>{text}</div>;
  }
  return <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)', fontStyle: 'italic' }}>(No message body — the email had no text/HTML content, or its body could not be retrieved.)</div>;
}

export default function EmailOfficial() {
  const [box, setBox] = useState('inbox');
  const [rows, setRows] = useState(null);
  const [unread, setUnread] = useState(0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [openMsg, setOpenMsg] = useState(null);
  const [opening, setOpening] = useState(false);

  const [composeOpen, setComposeOpen] = useState(false);
  const [replyTo, setReplyTo] = useState(null);
  const [form, setForm] = useState({ to: '', cc: '', subject: '', body: '' });
  const [attachments, setAttachments] = useState([]);
  const [sending, setSending] = useState(false);

  const onFiles = async (e) => {
    const files = Array.from(e.target.files || []);
    e.target.value = '';
    const read = (file) => new Promise((resolve, reject) => {
      const r = new FileReader();
      r.onload = () => resolve({ filename: file.name, content: (r.result || '').toString().split(',')[1] || '' });
      r.onerror = reject;
      r.readAsDataURL(file);
    });
    try {
      const added = await Promise.all(files.map(read));
      const next = [...attachments, ...added];
      const total = next.reduce((s, a) => s + (a.content ? a.content.length : 0), 0);
      if (total > 3 * 1024 * 1024) return alert('Attachments too large (max ~2 MB total).');
      setAttachments(next);
    } catch (err) { alert('Could not read the file.'); }
  };
  const removeAttachment = (i) => setAttachments(attachments.filter((_, idx) => idx !== i));

  const load = useCallback((silent) => {
    if (!silent) setLoading(true);
    api.listOfficialEmails(box, 50)
      .then(r => { setRows(r.emails || []); setUnread(r.unread || 0); })
      .catch(e => setError(e.message))
      .finally(() => setLoading(false));
  }, [box]);

  useEffect(() => { load(); }, [load]);
  usePolling(() => load(true), 60000, [load]);

  const openMessage = async (m) => {
    setOpening(true);
    try {
      const res = await api.getOfficialEmail(m.message_id);
      setOpenMsg(res);
      if (box === 'inbox' && !m.is_read) load(true);
    } catch (e) { alert(e.message); } finally { setOpening(false); }
  };

  const startCompose = () => {
    setReplyTo(null);
    setForm({ to: '', cc: '', subject: '', body: '' });
    setAttachments([]);
    setComposeOpen(true);
  };
  const startReply = (msg) => {
    setReplyTo(msg.message_id);
    setForm({ to: '', cc: '', subject: '', body: '' });
    setAttachments([]);
    setComposeOpen(true);
  };

  const submitSend = async (e) => {
    e.preventDefault();
    if (!form.body.trim()) return alert('Please write a message.');
    setSending(true);
    try {
      const att = attachments.length ? attachments : undefined;
      if (replyTo) {
        await api.replyOfficialEmail(replyTo, form.body.trim(), att);
      } else {
        if (!form.to.trim()) return alert('Recipient is required.');
        if (!form.subject.trim()) return alert('Subject is required.');
        await api.sendOfficialEmail(form.to.trim(), form.cc.trim(), form.subject.trim(), form.body.trim(), att);
      }
      setComposeOpen(false);
      setOpenMsg(null);
      setBox('sent');
      load();
    } catch (err) {
      alert(err.message);
    } finally {
      setSending(false);
    }
  };

  return (
    <div style={{ padding: 20 }}>
      <h2 style={{ marginBottom: 4 }}>✉️ Mail (official)</h2>
      <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: 12 }}>chhath@shaharpura.com</p>

      <div className="subtabs">
        <button className={`subtab-btn ${box === 'inbox' ? 'active' : ''}`} onClick={() => { setBox('inbox'); setOpenMsg(null); }}>
          Inbox{unread > 0 ? ` (${unread})` : ''}
        </button>
        <button className={`subtab-btn ${box === 'sent' ? 'active' : ''}`} onClick={() => { setBox('sent'); setOpenMsg(null); }}>Sent</button>
      </div>

      {error && <div className="error-banner">{error}</div>}
      {loading && <div className="inline-spinner">Loading mailbox...</div>}

      {!loading && !error && (rows || []).length === 0 && (
        <div className="glass-card" style={{ textAlign: 'center', padding: 20 }}>
          {box === 'inbox' ? 'No emails received yet.' : 'No emails sent yet.'}
        </div>
      )}

      {!loading && !error && (rows || []).map((m, i) => {
        const who = box === 'inbox' ? m.from_addr : m.to_addr;
        const unreadRow = box === 'inbox' && !m.is_read;
        return (
          <div
            className="glass-card"
            style={{ padding: 12, marginBottom: 8, cursor: 'pointer', borderLeft: unreadRow ? '3px solid var(--primary, #d97706)' : '3px solid transparent' }}
            key={m.message_id || i}
            onClick={() => openMessage(m)}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', gap: 8, flexWrap: 'wrap' }}>
              <strong style={{ fontWeight: unreadRow ? 700 : 500 }}>{who || '(unknown)'}</strong>
              <span style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>{fmtDate(m.created_at)}</span>
            </div>
            <div style={{ fontSize: '0.88rem', marginTop: 2 }}>{m.subject || '(no subject)'}</div>
            {box === 'sent' && m.status === 'failed' && <span className="badge badge-warn" style={{ marginTop: 6 }}>failed</span>}
          </div>
        );
      })}

      <button className="fab" onClick={startCompose} title="Compose"><span className="material-icons-round">edit</span></button>

      {}
      <Modal open={!!openMsg} onClose={() => setOpenMsg(null)}>
        {opening && <div className="inline-spinner">Opening...</div>}
        {openMsg && (
          <>
            <h3 style={{ marginBottom: 4 }}>{openMsg.message.subject || '(no subject)'}</h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10, marginTop: 10 }}>
              {(openMsg.thread || [openMsg.message]).map((t, i) => (
                <div key={t.message_id || i} className="glass-card" style={{ padding: 12, background: t.direction === 'inbound' ? '#f9fafb' : '#eef6ff' }}>
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginBottom: 6 }}>
                    <strong>{t.direction === 'inbound' ? t.from_addr : 'You (chhath@shaharpura.com)'}</strong>
                    {t.direction === 'inbound' ? '' : ` → ${t.to_addr}`} · {fmtDate(t.created_at)}
                    {t.status === 'failed' ? ' · failed' : ''}
                  </div>
                  <BodyView html={t.body_html} text={t.body_text} />
                  {Array.isArray(t.attachments) && t.attachments.length > 0 && (
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginTop: 8 }}>
                      {t.attachments.map((a, ai) => (
                        <span key={ai} className="badge" style={{ background: '#eef2ff', color: '#3730a3' }}>📎 {a.filename || 'attachment'}</span>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>
            <button className="btn-submit" style={{ marginTop: 14 }} onClick={() => startReply(openMsg.message)}>Reply</button>
          </>
        )}
      </Modal>

      {}
      <Modal open={composeOpen} onClose={() => setComposeOpen(false)}>
        <h3 style={{ marginBottom: 12 }}>{replyTo ? 'Reply' : 'Compose'}</h3>
        <form onSubmit={submitSend}>
          {!replyTo && (
            <>
              <div className="form-group">
                <label>To</label>
                <input type="email" value={form.to} onChange={e => setForm({ ...form, to: e.target.value })} placeholder="recipient@example.com" />
              </div>
              <div className="form-group">
                <label>Cc (optional)</label>
                <input type="email" value={form.cc} onChange={e => setForm({ ...form, cc: e.target.value })} placeholder="optional" />
              </div>
              <div className="form-group">
                <label>Subject</label>
                <input value={form.subject} onChange={e => setForm({ ...form, subject: e.target.value })} />
              </div>
            </>
          )}
          <div className="form-group">
            <label>Message</label>
            <textarea rows={8} value={form.body} onChange={e => setForm({ ...form, body: e.target.value })} style={{ width: '100%', padding: 10, borderRadius: 8, border: '1px solid #ddd' }} />
          </div>
          <div className="form-group">
            <label style={{ display: 'inline-flex', alignItems: 'center', gap: 6, cursor: 'pointer' }}>
              <span className="material-icons-round" style={{ fontSize: 18 }}>attach_file</span> Attach files (≤ ~2 MB total)
              <input type="file" multiple onChange={onFiles} style={{ display: 'none' }} />
            </label>
            {attachments.length > 0 && (
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginTop: 6 }}>
                {attachments.map((a, i) => (
                  <span key={i} className="badge" style={{ background: '#eef2ff', color: '#3730a3', display: 'inline-flex', alignItems: 'center', gap: 4 }}>
                    📎 {a.filename}
                    <span className="material-icons-round" style={{ fontSize: 14, cursor: 'pointer' }} onClick={() => removeAttachment(i)}>close</span>
                  </span>
                ))}
              </div>
            )}
          </div>
          <button className="btn-submit" disabled={sending}>{sending ? 'Sending...' : (replyTo ? 'Send Reply' : 'Send')}</button>
        </form>
      </Modal>
    </div>
  );
}

// mgmt/frontend-svelte/src/lib/views/EmailOfficial.svelte
<script lang="ts">
  // Ported from React views/EmailOfficial.jsx — official mailbox (chhath@...):
  // inbox/sent list, read a thread, compose/reply with attachments. 60s poll.
  import DOMPurify from 'dompurify';
  import { api } from '$lib/api';
  import { startPolling } from '$lib/polling';
  import Modal from '$lib/components/Modal.svelte';

  function fmtDate(s: string): string {
    if (!s) return '';
    const d = new Date(s);
    return isNaN(d.getTime()) ? s : d.toLocaleString();
  }

  let box = $state('inbox');
  let rows = $state<any[] | null>(null);
  let unread = $state(0);
  let loading = $state(true);
  let error = $state('');
  let openMsg = $state<any>(null);
  let opening = $state(false);

  let composeOpen = $state(false);
  let replyTo = $state<string | null>(null);
  let form = $state({ to: '', cc: '', subject: '', body: '' });
  let attachments = $state<any[]>([]);
  let sending = $state(false);

  async function onFiles(e: Event) {
    const input = e.currentTarget as HTMLInputElement;
    const files = Array.from(input.files || []);
    input.value = '';
    const read = (file: File) => new Promise<any>((resolve, reject) => {
      const r = new FileReader();
      r.onload = () => resolve({ filename: file.name, content: (r.result || '').toString().split(',')[1] || '' });
      r.onerror = reject;
      r.readAsDataURL(file);
    });
    try {
      const added = await Promise.all(files.map(read));
      const next = [...attachments, ...added];
      const total = next.reduce((s, a) => s + (a.content ? a.content.length : 0), 0);
      if (total > 3 * 1024 * 1024) { alert('Attachments too large (max ~2 MB total).'); return; }
      attachments = next;
    } catch (err) { alert('Could not read the file.'); }
  }
  function removeAttachment(i: number) { attachments = attachments.filter((_, idx) => idx !== i); }

  function load(silent?: boolean) {
    if (!silent) loading = true;
    api.listOfficialEmails(box, 50)
      .then((r: any) => { rows = r.emails || []; unread = r.unread || 0; })
      .catch((e: Error) => (error = e.message))
      .finally(() => (loading = false));
  }

  // React: useEffect on [box] (load) + 60s poll.
  let lastBox = '__init__';
  $effect(() => {
    if (box === lastBox) return;
    lastBox = box;
    load();
  });
  $effect(() => startPolling(() => load(true), 60000));

  async function openMessage(m: any) {
    opening = true;
    try {
      const res: any = await api.getOfficialEmail(m.message_id);
      openMsg = res;
      if (box === 'inbox' && !m.is_read) load(true);
    } catch (e) { alert((e as Error).message); } finally { opening = false; }
  }

  function startCompose() {
    replyTo = null;
    form = { to: '', cc: '', subject: '', body: '' };
    attachments = [];
    composeOpen = true;
  }
  function startReply(msg: any) {
    replyTo = msg.message_id;
    form = { to: '', cc: '', subject: '', body: '' };
    attachments = [];
    composeOpen = true;
  }

  async function submitSend(e: Event) {
    e.preventDefault();
    if (!form.body.trim()) { alert('Please write a message.'); return; }
    sending = true;
    try {
      const att = attachments.length ? attachments : undefined;
      if (replyTo) {
        await api.replyOfficialEmail(replyTo, form.body.trim(), att);
      } else {
        if (!form.to.trim()) { alert('Recipient is required.'); sending = false; return; }
        if (!form.subject.trim()) { alert('Subject is required.'); sending = false; return; }
        await api.sendOfficialEmail(form.to.trim(), form.cc.trim(), form.subject.trim(), form.body.trim(), att);
      }
      composeOpen = false;
      openMsg = null;
      box = 'sent';
      load();
    } catch (err) {
      alert((err as Error).message);
    } finally {
      sending = false;
    }
  }

  function bodyHtml(html: string, text: string): { kind: 'html' | 'text' | 'empty'; value: string } {
    if (html && html.trim()) return { kind: 'html', value: DOMPurify.sanitize(html, { USE_PROFILES: { html: true } }) };
    if (text && text.trim()) return { kind: 'text', value: text };
    return { kind: 'empty', value: '' };
  }
</script>

<div style="padding:20px;">
  <h2 style="margin-bottom:4px;">✉️ Mail (official)</h2>
  <p style="font-size:0.8rem; color:var(--text-muted); margin-bottom:12px;">chhath@shaharpura.com</p>

  <div class="subtabs">
    <button class="subtab-btn {box === 'inbox' ? 'active' : ''}" onclick={() => { box = 'inbox'; openMsg = null; }}>
      Inbox{unread > 0 ? ` (${unread})` : ''}
    </button>
    <button class="subtab-btn {box === 'sent' ? 'active' : ''}" onclick={() => { box = 'sent'; openMsg = null; }}>Sent</button>
  </div>

  {#if error}<div class="error-banner">{error}</div>{/if}
  {#if loading}<div class="inline-spinner">Loading mailbox...</div>{/if}

  {#if !loading && !error && (rows || []).length === 0}
    <div class="glass-card" style="text-align:center; padding:20px;">
      {box === 'inbox' ? 'No emails received yet.' : 'No emails sent yet.'}
    </div>
  {/if}

  {#if !loading && !error}
    {#each rows || [] as m, i (m.message_id || i)}
      {@const who = box === 'inbox' ? m.from_addr : m.to_addr}
      {@const unreadRow = box === 'inbox' && !m.is_read}
      <!-- svelte-ignore a11y_click_events_have_key_events -->
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <div
        class="glass-card"
        style="padding:12px; margin-bottom:8px; cursor:pointer; border-left:{unreadRow ? '3px solid var(--primary, #d97706)' : '3px solid transparent'};"
        onclick={() => openMessage(m)}
      >
        <div style="display:flex; justify-content:space-between; gap:8px; flex-wrap:wrap;">
          <strong style="font-weight:{unreadRow ? 700 : 500};">{who || '(unknown)'}</strong>
          <span style="font-size:0.72rem; color:var(--text-muted);">{fmtDate(m.created_at)}</span>
        </div>
        <div style="font-size:0.88rem; margin-top:2px;">{m.subject || '(no subject)'}</div>
        {#if box === 'sent' && m.status === 'failed'}<span class="badge badge-warn" style="margin-top:6px;">failed</span>{/if}
      </div>
    {/each}
  {/if}

  <button class="fab" onclick={startCompose} title="Compose"><span class="material-icons-round">edit</span></button>

  <Modal open={!!openMsg} onClose={() => (openMsg = null)}>
    {#if opening}<div class="inline-spinner">Opening...</div>{/if}
    {#if openMsg}
      <h3 style="margin-bottom:4px;">{openMsg.message.subject || '(no subject)'}</h3>
      <div style="display:flex; flex-direction:column; gap:10px; margin-top:10px;">
        {#each (openMsg.thread || [openMsg.message]) as t, i (t.message_id || i)}
          {@const body = bodyHtml(t.body_html, t.body_text)}
          <div class="glass-card" style="padding:12px; background:{t.direction === 'inbound' ? '#f9fafb' : '#eef6ff'};">
            <div style="font-size:0.75rem; color:var(--text-muted); margin-bottom:6px;">
              <strong>{t.direction === 'inbound' ? t.from_addr : 'You (chhath@shaharpura.com)'}</strong>
              {t.direction === 'inbound' ? '' : ` → ${t.to_addr}`} · {fmtDate(t.created_at)}{t.status === 'failed' ? ' · failed' : ''}
            </div>
            {#if body.kind === 'html'}
              <div style="font-size:0.9rem; line-height:1.5;">{@html body.value}</div>
            {:else if body.kind === 'text'}
              <div style="font-size:0.9rem; line-height:1.5; white-space:pre-wrap;">{body.value}</div>
            {:else}
              <div style="font-size:0.85rem; color:var(--text-muted); font-style:italic;">(No message body — the email had no text/HTML content, or its body could not be retrieved.)</div>
            {/if}
            {#if Array.isArray(t.attachments) && t.attachments.length > 0}
              <div style="display:flex; flex-wrap:wrap; gap:6px; margin-top:8px;">
                {#each t.attachments as a, ai (ai)}
                  <span class="badge" style="background:#eef2ff; color:#3730a3;">📎 {a.filename || 'attachment'}</span>
                {/each}
              </div>
            {/if}
          </div>
        {/each}
      </div>
      <button class="btn-submit" style="margin-top:14px;" onclick={() => startReply(openMsg.message)}>Reply</button>
    {/if}
  </Modal>

  <Modal open={composeOpen} onClose={() => (composeOpen = false)}>
    <h3 style="margin-bottom:12px;">{replyTo ? 'Reply' : 'Compose'}</h3>
    <form onsubmit={submitSend}>
      {#if !replyTo}
        <div class="form-group">
          <label>To</label>
          <input type="email" bind:value={form.to} placeholder="recipient@example.com" />
        </div>
        <div class="form-group">
          <label>Cc (optional)</label>
          <input type="email" bind:value={form.cc} placeholder="optional" />
        </div>
        <div class="form-group">
          <label>Subject</label>
          <input bind:value={form.subject} />
        </div>
      {/if}
      <div class="form-group">
        <label>Message</label>
        <textarea rows={8} bind:value={form.body} style="width:100%; padding:10px; border-radius:8px; border:1px solid #ddd;"></textarea>
      </div>
      <div class="form-group">
        <label style="display:inline-flex; align-items:center; gap:6px; cursor:pointer;">
          <span class="material-icons-round" style="font-size:18px;">attach_file</span> Attach files (≤ ~2 MB total)
          <input type="file" multiple onchange={onFiles} style="display:none;" />
        </label>
        {#if attachments.length > 0}
          <div style="display:flex; flex-wrap:wrap; gap:6px; margin-top:6px;">
            {#each attachments as a, i (i)}
              <span class="badge" style="background:#eef2ff; color:#3730a3; display:inline-flex; align-items:center; gap:4px;">
                📎 {a.filename}
                <!-- svelte-ignore a11y_click_events_have_key_events -->
                <!-- svelte-ignore a11y_no_static_element_interactions -->
                <span class="material-icons-round" style="font-size:14px; cursor:pointer;" onclick={() => removeAttachment(i)}>close</span>
              </span>
            {/each}
          </div>
        {/if}
      </div>
      <button class="btn-submit" disabled={sending}>{sending ? 'Sending...' : (replyTo ? 'Send Reply' : 'Send')}</button>
    </form>
  </Modal>
</div>
