// mgmt/frontend/src/views/Home.jsx
import { useState, useMemo, useEffect, useDeferredValue } from 'react';
import { api, fmt, reportClientError } from '../api.js';
import { safeImport } from '../chunkGuard.js';
import { useViewData } from '../useViewData.js';
import { invalidate } from '../cache.js';
import Modal from '../components/Modal.jsx';
import SearchableSelect from '../components/SearchableSelect.jsx';
import QuickAddUser from '../components/QuickAddUser.jsx';
import RowActions from '../components/RowActions.jsx';
import QueueStatus from '../components/QueueStatus.jsx';

import { canAddView } from '../permissions.js';
import { useDropdownList } from '../useDropdownList.js';
import { isTruthyFlag } from '../flags.js';

function autoGenerateDocType(payload) {
  if (payload['Is Resell'] === 'TRUE') return null;
  const type = payload['Contribution Type'];
  if (type === '1') return 'receipt';
  if (type === '2') return 'samaan';
  if (type === '3') return payload['Certificate Or Receipt'] === 'Certificate' ? 'certificate' : 'receipt_work';
  return null;
}

const AUTO_GENERATE_FETCH = {
  receipt: (api, rowIndex, year) => api.getReceiptData(rowIndex, year),
  receipt_work: (api, rowIndex, year) => api.getReceiptData(rowIndex, year),
  certificate: (api, rowIndex, year) => api.getCertificateData(rowIndex, year),
  samaan: (api, rowIndex, year) => api.getSamaanData(rowIndex, year),
};
const AUTO_GENERATE_DOC_NO_KEY = { receipt: 'RECEIPT_NO', receipt_work: 'RECEIPT_NO', certificate: 'CERT_NO', samaan: 'SAMAAN_NO' };
const DOC_TYPE_LABELS = { receipt: 'Receipt', receipt_work: 'Receipt — Work', certificate: 'Certificate', samaan: 'Material Receipt' };

export default function Home({ year, users, onUserCreated, role, editable }) {

  const { data, loading, error, refresh } = useViewData(`home:${year}`, () => api.getHome(year), [year]);
  const { options: paymentModeOptions, hindiOf: paymentModeHindiOf } = useDropdownList('Payment Mode');
  const [search, setSearch] = useState('');
  const [showAdd, setShowAdd] = useState(false);
  const [showQuickAdd, setShowQuickAdd] = useState(false);
  const [form, setForm] = useState({
    Name: '', Amount: '', 'Payment Mode': 'Cash', UTR: '',
    Date: new Date().toISOString().slice(0, 10), 'Contribution Type': '1',
    Detail: '', 'Certificate Or Receipt': 'Receipt', 'Is Resell': false,
  });
  const [saving, setSaving] = useState(false);
  const [savingStep, setSavingStep] = useState('');
  const [postSaveWarning, setPostSaveWarning] = useState('');
  const [queueBump, setQueueBump] = useState(0);
  const [editing, setEditing] = useState(null);
  const [history, setHistory] = useState(null);
  const [historyLoading, setHistoryLoading] = useState(false);

  const userMap = useMemo(() => {
    const m = {};
    (users || []).forEach(u => { m[u.ID] = u; });
    return m;
  }, [users]);

  const userOptions = useMemo(() => (users || []).map(u => ({ value: u.ID, label: u.Name, sub: u.Village })), [users]);

  useEffect(() => {
    if (!form.Name) { setHistory(null); return; }
    setHistoryLoading(true);
    api.getUserHistory(form.Name).then(setHistory).catch(() => setHistory(null)).finally(() => setHistoryLoading(false));
  }, [form.Name]);

  const deferredSearch = useDeferredValue(search);
  const filtered = useMemo(() => {
    const q = deferredSearch.toLowerCase();
    return (data?.collections || []).filter(r => {
      if (isTruthyFlag(r['Is Resell'])) return (r.Detail || '').toLowerCase().includes(q);
      const u = userMap[r.Name] || { Name: 'Unknown User' };
      return (u.Name || '').toLowerCase().includes(q);
    });
  }, [data, deferredSearch, userMap]);

  const RENDER_CAP = 300;
  const visible = filtered.slice(0, RENDER_CAP);

  const submit = async (e) => {
    e.preventDefault();
    const isMoney = form['Contribution Type'] === '1';
    const isResell = isMoney && !!form['Is Resell'];
    const isUtrMode = isMoney && !isResell && (form['Payment Mode'] === 'UPI' || form['Payment Mode'] === 'Online');
    if (isResell) {
      if (!form.Detail.trim()) return alert("Resold item's name is required");
      if (!form.Amount) return alert('Amount is required');
    } else {
      if (!form.Name) return alert('Please select a contributor');
      if (isMoney && !form.Amount) return alert('Amount is required');
      if (!isMoney && !form.Detail.trim()) return alert('Detail is required (what was given / what work was done)');
    }
    setSaving(true);
    try {
      const payload = {
        Name: isResell ? '' : form.Name,
        'Payment Mode': isMoney ? form['Payment Mode'] : '',
        UTR: isUtrMode ? form.UTR : '',
        Date: form.Date,
        'Contribution Type': form['Contribution Type'],
        Amount: (isMoney || isResell) ? form.Amount : '',
        Detail: (isMoney && !isResell) ? '' : form.Detail,
        'Certificate Or Receipt': form['Contribution Type'] === '3' ? form['Certificate Or Receipt'] : '',
        'Is Resell': isResell ? 'TRUE' : 'FALSE',
      };
      let savedRowIndex;
      let genYear;
      const isNewEntry = !editing;
      if (editing) {
        genYear = editing.Year;
        savedRowIndex = editing.__rowIndex;
        // Neither `Sl. No.` (the receipt number) nor `Created By` is sent: the server owns
        // both and REJECTS them, which is what broke every edit here. An unsent column keeps
        // its stored value, because updateRecord builds `SET` from the keys it receives.
        await api.updateRecord('COLLECTIONS', editing.__rowIndex, { Year: editing.Year, ...payload });
      } else {
        genYear = year === 'All' ? new Date().getFullYear() : year;
        const res = await api.saveRecord('COLLECTIONS', { Year: genYear, ...payload });
        savedRowIndex = res.rowIndex;
      }
      invalidate('home:');

      const docType = autoGenerateDocType(payload);
      const genPayload = { Year: genYear, ...payload };
      const warnings = [];

      let filled = { filledBase64: '', fileName: '' };
      if (docType && savedRowIndex) {
        setSavingStep('Preparing document...');
        const fillResult = await fillDocxForQueue(docType, savedRowIndex, genYear);
        filled = { filledBase64: fillResult.filledBase64 || '', fileName: fillResult.fileName || '' };
        if (fillResult.warning) warnings.push(fillResult.warning);
      }

      setSavingStep('Adding to the queue...');
      try {
        await api.enqueueCollectionJob({
          docType: docType || '',
          year: genYear,
          rowIndex: savedRowIndex,
          recordId: (docType && savedRowIndex) ? `${docType}-${genYear}-${savedRowIndex}` : '',
          isNewEntry,
          payload: genPayload,
          filledBase64: filled.filledBase64,
          fileName: filled.fileName,
        });
        api.processCollectionQueue().catch(() => {  });
        warnings.push('The PDF and WhatsApp message have been queued in the background — they will complete shortly.');
      } catch (err) {
        reportClientError('Home', 'enqueueCollectionJob failed — falling back to inline', err,
          { docType, genYear, rowIndex: savedRowIndex });
        let fileLink = '';
        if (docType && savedRowIndex && filled.filledBase64) {
          try {
            const res = await api.convertDocxToPdf(docType, genYear,
              `${docType}-${genYear}-${savedRowIndex}`, filled.filledBase64, filled.fileName);
            fileLink = (res && res.publicLink) || '';
          } catch (e2) { warnings.push('PDF generation failed: ' + e2.message); }
        }
        if (isNewEntry) {
          try {
            await api.queueCollectionMessages(genPayload, savedRowIndex, fileLink);
          } catch (e3) {
            warnings.push('The WhatsApp message could not be queued: ' + e3.message);
          }
        }
      }

      setPostSaveWarning(warnings.join(' | '));
      setQueueBump(n => n + 1);
      closeModal();
      refresh();
    } catch (err) {
      alert(err.message);
    } finally {
      setSaving(false);
      setSavingStep('');
    }
  };

  const fillDocxForQueue = async (docType, rowIndex, genYear) => {
    const recordId = `${docType}-${genYear}-${rowIndex}`;
    try {
      let docxRow;
      try {
        docxRow = await api.getDocxTemplateForDoc(docType, genYear);
      } catch (err) {
        reportClientError('Home', `autoPdf template load failed for ${docType} ${genYear}`, err,
          { docType, genYear, rowIndex });
        return { filledBase64: '', fileName: '', warning: `PDF template failed to load: ${err.message}` };
      }
      if (!docxRow || (!docxRow.base64 && !docxRow.downloadUrl)) {
        const label = DOC_TYPE_LABELS[docType] || docType;
        return {
          filledBase64: '', fileName: '',
          warning: `No ${label} template is uploaded for ${genYear}, so no document could be attached. `
            + `The entry was saved. To attach a document, upload a ${label} template under Document Templates.`,
        };
      }

      const dataFetcher = AUTO_GENERATE_FETCH[docType];
      if (!dataFetcher) return { filledBase64: '', fileName: '', warning: '' };
      const data = await dataFetcher(api, rowIndex, genYear);
      const docNoKey = AUTO_GENERATE_DOC_NO_KEY[docType];

      const { fillDocxTemplateFromRow, getLastRenderReport } = await safeImport(() => import('../docxFill.js'), 'docxFill');
      const { generateQrDataUrl, publicRecordUrl } = await safeImport(() => import('../qrCode.js'), 'qrCode');

      let qrCode = '';
      try {
        qrCode = await generateQrDataUrl(publicRecordUrl(recordId));
      } catch (qrErr) {
        reportClientError('Home', `autoPdf QR generation failed for ${recordId}`, qrErr,
          { docType, genYear, rowIndex, recordId });
      }

      const placeholders = { ...data.placeholders, GENERATED_AT: new Date().toLocaleString('en-IN'), QR_CODE: qrCode };
      const filledBase64 = await fillDocxTemplateFromRow(docxRow, placeholders);

      const rep = getLastRenderReport();
      if (rep.missingTags.length) {
        reportClientError('Home', `autoPdf unresolved placeholders for ${recordId}`, null,
          { docType, genYear, recordId, missingTags: [...new Set(rep.missingTags)] });
      }

      const fileName = `${docType}-${placeholders[docNoKey]}.docx`;
      return { filledBase64, fileName, warning: qrCode ? '' : 'The QR in the PDF is blank.' };
    } catch (err) {
      reportClientError('Home', `autoPdf fill failed for ${recordId}`, err, { docType, genYear, rowIndex });
      return { filledBase64: '', fileName: '', warning: 'The document could not be prepared: ' + err.message };
    }
  };

  const closeModal = () => {
    setShowAdd(false);
    setEditing(null);
    setForm({
      Name: '', Amount: '', 'Payment Mode': 'Cash', UTR: '',
      Date: new Date().toISOString().slice(0, 10), 'Contribution Type': '1',
      Detail: '', 'Certificate Or Receipt': 'Receipt', 'Is Resell': false,
    });
  };

  const openEdit = (r) => {
    setEditing(r);
    setForm({
      Name: r.Name, Amount: r.Amount, 'Payment Mode': r['Payment Mode'] || 'Cash', UTR: r.UTR || '',
      Date: r.Date || new Date().toISOString().slice(0, 10),
      'Contribution Type': (r['Contribution Type'] ?? '').toString() || '1', Detail: r.Detail || '', 'Certificate Or Receipt': r['Certificate Or Receipt'] || 'Receipt',
      'Is Resell': r['Is Resell'] === 'TRUE' || r['Is Resell'] === true,
    });
    setShowAdd(true);
  };

  const remove = async (r) => {
    if (!confirm('Delete this collection entry?')) return;
    try {
      await api.deleteRecord('COLLECTIONS', r.__rowIndex);
      invalidate('home:');
      refresh();
    } catch (err) {
      alert(err.message);
    }
  };

  if (loading) return <div className="inline-spinner">Loading budget...</div>;
  if (error) return <div className="error-banner">{error}</div>;
  if (!data) return <div className="inline-spinner">Loading budget...</div>;

  return (
    <>
      <div className="glass-card budget-card">
        <h2 style={{ marginBottom: 15 }}>{year === 'All' ? 'Lifetime' : year} Budget Overview</h2>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 10 }}>
          <span>(+) Past Loan Returned</span><strong>{fmt(data.pastRet)}</strong>
        </div>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 15 }}>
          <span>(+) Collection</span><strong style={{ color: '#34D399' }}>+{fmt(data.totCol)}</strong>
        </div>
        <div style={{ borderTop: '1px dashed #4B5563', paddingTop: 15, display: 'flex', justifyContent: 'space-between' }}>
          <strong>TOTAL BUDGET</strong><strong style={{ color: 'var(--primary-saffron)', fontSize: '1.5rem' }}>{fmt(data.totBudget)}</strong>
        </div>
      </div>

      <div className="grid-2" style={{ marginBottom: 20 }}>
        <div className="stat-box" style={{ borderColor: 'var(--danger)' }}>
          <div style={{ fontSize: '0.8rem', color: 'gray' }}>Total Expense</div>
          <div style={{ fontSize: '1.2rem', fontWeight: 'bold', color: 'var(--danger)' }}>{fmt(data.totExp)}</div>
        </div>
        <div className="stat-box" style={{ borderColor: 'var(--success)' }}>
          <div style={{ fontSize: '0.8rem', color: 'gray' }}>Net Surplus</div>
          <div style={{ fontSize: '1.2rem', fontWeight: 'bold', color: 'var(--success)' }}>{fmt(data.surplus)}</div>
        </div>
      </div>

      {postSaveWarning && (
        <div style={{ background: '#FEF3C7', color: '#92400E', borderRadius: 8, padding: '10px 12px', fontSize: '0.85rem', marginBottom: 12, display: 'flex', justifyContent: 'space-between', gap: 8 }}>
          <span>⚠️ The entry was saved, but: {postSaveWarning}</span>
          <span style={{ cursor: 'pointer', fontWeight: 700 }} onClick={() => setPostSaveWarning('')}>×</span>
        </div>
      )}

      {}
      <QueueStatus refreshKey={queueBump} />

      <h3 style={{ marginBottom: 15 }}>Collections (Contribution)</h3>
      <input placeholder="Search Contribution Data..." style={{ marginBottom: 15 }} value={search} onChange={e => setSearch(e.target.value)} />

      {
}
      {data.hasMore && (
        <div style={{ background: '#EFF6FF', color: '#1E40AF', borderRadius: 8, padding: '8px 12px', fontSize: '0.85rem', marginBottom: 12 }}>
          Showing the {data.shownRows} most recent of {data.totalRows} contributions.
          The totals above cover all of them. Select a specific year to see its complete list.
        </div>
      )}
      <div className="glass-card">
        {filtered.length === 0 && <div style={{ textAlign: 'center', padding: 20 }}>No records found.</div>}
        {visible.map((r) => {
          const isResellRow = r['Is Resell'] === 'TRUE' || r['Is Resell'] === true;
          const u = isResellRow ? null : (userMap[r.Name] || { Name: 'Unknown User', Village: '-' });
          return (
            <div className="data-row" key={r.__rowIndex}>
              <div>
                {isResellRow ? (
                  <strong style={{ display: 'block' }}>
                    ♻️ Resell: {r.Detail || '-'} {year === 'All' && <span style={{ color: 'var(--primary-saffron)', fontSize: '0.75rem' }}>[{r.Year}]</span>}
                  </strong>
                ) : (
                  <>
                    <strong style={{ display: 'block' }}>{u.Name} | {u.Designation || '-'} {year === 'All' && <span style={{ color: 'var(--primary-saffron)', fontSize: '0.75rem' }}>[{r.Year}]</span>}</strong>
                    <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>{u["Father's Name"] || '-'} | {u.Village || '-'}</span>
                  </>
                )}
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 4 }}>
                {((r['Contribution Type'] ?? '').toString() || '1') === '1' ? (
                  <strong style={{ color: 'var(--success)' }}>+{fmt(r.Amount)}</strong>
                ) : (
                  <span className="badge" style={{ background: '#DBEAFE', color: '#1E40AF' }}>
                    {(r['Contribution Type'] ?? '').toString() === '2' ? 'Material' : 'Service'}{r['Certificate Or Receipt'] === 'Certificate' ? ' — Certificate' : ''}
                  </span>
                )}
                {!isResellRow && r.Detail && <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', maxWidth: 180, textAlign: 'right' }}>{r.Detail}</span>}
                {r['Payment Mode'] && <span className="badge" style={{ background: '#f3f4f6', color: '#374151' }}>{r['Payment Mode']}{paymentModeHindiOf(r['Payment Mode']) ? ` (${paymentModeHindiOf(r['Payment Mode'])})` : ''}</span>}
                {r.UTR && <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>UTR: {r.UTR}</span>}
                <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                  <RowActions role={role} disabled={!editable} onEdit={() => openEdit(r)} onDelete={() => remove(r)} />
                </div>
              </div>
            </div>
          );
        })}
        {filtered.length > RENDER_CAP && (
          <div style={{ textAlign: 'center', padding: 14, color: 'var(--text-muted)', fontSize: '0.85rem' }}>
            Showing {RENDER_CAP} of {filtered.length} matching rows — refine the search to narrow the list.
          </div>
        )}
      </div>

      {editable && canAddView(role, 'home') && (
        <button className="fab" onClick={() => setShowAdd(true)}><span className="material-icons-round">add</span></button>
      )}

      <Modal open={showAdd} onClose={closeModal}>
        <h3 style={{ marginBottom: 15 }}>{editing ? 'Edit Collection' : 'Add Collection'}</h3>
        <form onSubmit={submit}>
          <div className="form-group">
            <label>Contribution Type</label>
            <select
              value={form['Contribution Type']}
              onChange={e => setForm({ ...form, 'Contribution Type': e.target.value, 'Is Resell': e.target.value === '1' ? form['Is Resell'] : false })}
            >
              <option value="1">Cash (Money)</option>
              <option value="2">Material (Item)</option>
              <option value="3">Service (Work)</option>
            </select>
          </div>

          {form['Contribution Type'] === '1' && (
            <div className="form-group" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <input
                type="checkbox"
                id="isResell"
                checked={!!form['Is Resell']}
                onChange={e => setForm({ ...form, 'Is Resell': e.target.checked, Name: '' })}
                style={{ width: 'auto' }}
              />
              <label htmlFor="isResell" style={{ margin: 0 }}>This is an entry for a resold item (no contributor)</label>
            </div>
          )}

          {form['Contribution Type'] === '1' && form['Is Resell'] ? (
            <div className="form-group">
              <label>Resold Item Name</label>
              <input value={form.Detail} onChange={e => setForm({ ...form, Detail: e.target.value })} placeholder="e.g. Old utensils, clothes, etc." />
            </div>
          ) : (
            <div className="form-group">
              <label>Contributor</label>
              <SearchableSelect
                options={userOptions}
                value={form.Name}
                onChange={id => setForm({ ...form, Name: id })}
                placeholder="Search name or village..."
                onAddNew={() => setShowQuickAdd(true)}
              />
            </div>
          )}

          {form.Name && !form['Is Resell'] && (
            <div className="form-group" style={{ background: '#f9fafb', borderRadius: 8, padding: '10px 12px' }}>
              <label style={{ marginBottom: 6 }}>Last 5 Years Contribution</label>
              {historyLoading && <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Loading...</div>}
              {!historyLoading && (!history || history.length === 0) && <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>No prior contributions</div>}
              {!historyLoading && history && history.map(h => {
                const tags = [];
                if (h.HasSamaan) tags.push('Material');
                if (h.HasKaam) tags.push('Service');
                return (
                  <div key={h.Year} style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', padding: '3px 0' }}>
                    <span>{h.Year}</span>
                    <span>
                      {h.Amount > 0 && <strong style={{ color: 'var(--success)' }}>{fmt(h.Amount)}</strong>}
                      {tags.length > 0 && <span style={{ color: 'var(--text-muted)' }}>{h.Amount > 0 ? ' + ' : ''}{tags.join(', ')}</span>}
                    </span>
                  </div>
                );
              })}
            </div>
          )}

          {(form['Contribution Type'] === '1') ? (
            <div className="form-group">
              <label>Amount</label>
              <input type="number" value={form.Amount} onChange={e => setForm({ ...form, Amount: e.target.value })} />
            </div>
          ) : (
            <div className="form-group">
              <label>{form['Contribution Type'] === '2' ? 'What was given (Item Detail)' : 'What work was done (Work Detail)'}</label>
              <textarea rows={2} value={form.Detail} onChange={e => setForm({ ...form, Detail: e.target.value })} style={{ width: '100%', padding: 8, borderRadius: 8, border: '1px solid #ddd' }} />
            </div>
          )}

          {form['Contribution Type'] === '3' && (
            <div className="form-group">
              <label>Document Type</label>
              <select value={form['Certificate Or Receipt']} onChange={e => setForm({ ...form, 'Certificate Or Receipt': e.target.value })}>
                <option value="Receipt">Receipt</option>
                <option value="Certificate">Certificate</option>
              </select>
            </div>
          )}

          {form['Contribution Type'] === '1' && (
            <div className="form-group">
              <label>Payment Mode</label>
              <select value={form['Payment Mode']} onChange={e => setForm({ ...form, 'Payment Mode': e.target.value })}>
                {paymentModeOptions.map(p => (
                  <option key={p['English Value']} value={p['English Value']}>
                    {p['English Value']}{p['Hindi Label'] ? ` (${p['Hindi Label']})` : ''}
                  </option>
                ))}
              </select>
            </div>
          )}

          {form['Contribution Type'] === '1' && (form['Payment Mode'] === 'UPI' || form['Payment Mode'] === 'Online') && (
            <div className="form-group">
              <label>UTR / Transaction ID</label>
              <input value={form.UTR} onChange={e => setForm({ ...form, UTR: e.target.value })} placeholder="UPI/Bank UTR number" />
            </div>
          )}

          <div className="form-group">
            <label>Date</label>
            <input type="date" value={form.Date} onChange={e => setForm({ ...form, Date: e.target.value })} />
          </div>
          <button className="btn-submit" disabled={saving}>{saving ? (savingStep || 'Saving...') : 'Save'}</button>
        </form>
      </Modal>

      <QuickAddUser
        open={showQuickAdd}
        onClose={() => setShowQuickAdd(false)}
        onCreated={(id) => { onUserCreated(); setForm(f => ({ ...f, Name: id })); }}
      />

    </>
  );
}

// mgmt/frontend-svelte/src/lib/views/Home.svelte
<script lang="ts">
  // Ported from React views/Home.jsx — budget overview + collections list for a
  // year: add/edit/delete COLLECTIONS, contributor history, auto doc generation
  // (receipt/certificate/samaan) enqueued to the background queue, resell entries.
  import { api, fmt, reportClientError } from '$lib/api';
  import { safeImport } from '$lib/chunkGuard';
  import { createViewData, type ViewData } from '$lib/viewData';
  import { invalidate } from '$lib/cache';
  import Modal from '$lib/components/Modal.svelte';
  import SearchableSelect from '$lib/components/SearchableSelect.svelte';
  import QuickAddUser from '$lib/components/QuickAddUser.svelte';
  import RowActions from '$lib/components/RowActions.svelte';
  import QueueStatus from '$lib/components/QueueStatus.svelte';
  import { canAddView } from '$lib/permissions';
  import { createDropdownList } from '$lib/dropdownList';
  import { isTruthyFlag } from '$lib/flags';
  import { checkMoney } from '$lib/money';

  interface Props {
    year: string;
    users: any[];
    onUserCreated: () => void;
    role: string;
    editable: boolean;
  }
  let { year, users, onUserCreated, role, editable }: Props = $props();

  function autoGenerateDocType(payload: any): string | null {
    if (payload['Is Resell'] === 'TRUE') return null;
    const type = payload['Contribution Type'];
    if (type === '1') return 'receipt';
    if (type === '2') return 'samaan';
    if (type === '3') return payload['Certificate Or Receipt'] === 'Certificate' ? 'certificate' : 'receipt_work';
    return null;
  }

  const AUTO_GENERATE_FETCH: Record<string, (api: any, rowIndex: number, year: any) => Promise<any>> = {
    receipt: (api, rowIndex, year) => api.getReceiptData(rowIndex, year),
    receipt_work: (api, rowIndex, year) => api.getReceiptData(rowIndex, year),
    certificate: (api, rowIndex, year) => api.getCertificateData(rowIndex, year),
    samaan: (api, rowIndex, year) => api.getSamaanData(rowIndex, year)
  };
  const AUTO_GENERATE_DOC_NO_KEY: Record<string, string> = { receipt: 'RECEIPT_NO', receipt_work: 'RECEIPT_NO', certificate: 'CERT_NO', samaan: 'SAMAAN_NO' };
  const DOC_TYPE_LABELS: Record<string, string> = { receipt: 'Receipt', receipt_work: 'Receipt — Work', certificate: 'Certificate', samaan: 'Material Receipt' };

  const RENDER_CAP = 300;
  const BLANK = () => ({
    Name: '', Amount: '', 'Payment Mode': 'Cash', UTR: '',
    Date: new Date().toISOString().slice(0, 10), 'Contribution Type': '1',
    Detail: '', 'Certificate Or Receipt': 'Receipt', 'Is Resell': false
  });

  // Year-scoped home view.
  let view = $state<ViewData<any>>(createViewData(`home:${year}`, () => api.getHome(year)));
  let lastYear = year;
  $effect(() => {
    if (year !== lastYear) {
      lastYear = year;
      view = createViewData(`home:${year}`, () => api.getHome(year));
    }
  });
  let vs = $state({ data: undefined as any, loading: true, error: '' });
  $effect(() => view.subscribe((v) => (vs = v as any)));

  const paymentModeList = createDropdownList('Payment Mode');
  let paymentModeOptions = $state<any[]>([]);
  $effect(() => paymentModeList.subscribe((s) => (paymentModeOptions = s.options)));
  const paymentModeHindiOf = (v: string) => paymentModeList.hindiOf(v);

  let search = $state('');
  let showAdd = $state(false);
  let showQuickAdd = $state(false);
  let form = $state<any>(BLANK());
  let saving = $state(false);
  let savingStep = $state('');
  let postSaveWarning = $state('');
  let queueBump = $state(0);
  let editing = $state<any>(null);
  let history = $state<any[] | null>(null);
  let historyLoading = $state(false);

  let userMap = $derived.by(() => {
    const m: Record<string, any> = {};
    (users || []).forEach((u) => (m[u.ID] = u));
    return m;
  });
  let userOptions = $derived((users || []).map((u) => ({ value: u.ID, label: u.Name, sub: u.Village })));

  // Contribution history for the selected contributor (matches deps [form.Name]).
  let lastHistName = '__init__';
  $effect(() => {
    const name = form.Name;
    if (name === lastHistName) return;
    lastHistName = name;
    if (!name) { history = null; return; }
    historyLoading = true;
    api.getUserHistory(name)
      .then((h: any) => (history = h))
      .catch(() => (history = null))
      .finally(() => (historyLoading = false));
  });

  let filtered = $derived.by(() => {
    const q = search.toLowerCase();
    return (vs.data?.collections || []).filter((r: any) => {
      if (isTruthyFlag(r['Is Resell'])) return (r.Detail || '').toLowerCase().includes(q);
      const u = userMap[r.Name] || { Name: 'Unknown User' };
      return (u.Name || '').toLowerCase().includes(q);
    });
  });
  let visible = $derived(filtered.slice(0, RENDER_CAP));

  async function fillDocxForQueue(docType: string, rowIndex: number, genYear: any) {
    const recordId = `${docType}-${genYear}-${rowIndex}`;
    try {
      let docxRow: any;
      try {
        docxRow = await api.getDocxTemplateForDoc(docType, genYear);
      } catch (err) {
        reportClientError('Home', `autoPdf template load failed for ${docType} ${genYear}`, err as Error, { docType, genYear, rowIndex });
        return { filledBase64: '', fileName: '', warning: `PDF template failed to load: ${(err as Error).message}` };
      }
      if (!docxRow || (!docxRow.base64 && !docxRow.downloadUrl)) {
        const label = DOC_TYPE_LABELS[docType] || docType;
        return {
          filledBase64: '', fileName: '',
          warning: `No ${label} template is uploaded for ${genYear}, so no document could be attached. `
            + `The entry was saved. To attach a document, upload a ${label} template under Document Templates.`
        };
      }

      const dataFetcher = AUTO_GENERATE_FETCH[docType];
      if (!dataFetcher) return { filledBase64: '', fileName: '', warning: '' };
      const data = await dataFetcher(api, rowIndex, genYear);
      const docNoKey = AUTO_GENERATE_DOC_NO_KEY[docType];

      const { fillDocxTemplateFromRow, getLastRenderReport } = await safeImport(() => import('$lib/docxFill'), 'docxFill');
      const { generateQrDataUrl, publicRecordUrl } = await safeImport(() => import('$lib/qrCode'), 'qrCode');

      let qrCode = '';
      try {
        qrCode = await generateQrDataUrl(publicRecordUrl(recordId));
      } catch (qrErr) {
        reportClientError('Home', `autoPdf QR generation failed for ${recordId}`, qrErr as Error, { docType, genYear, rowIndex, recordId });
      }

      const placeholders = { ...data.placeholders, GENERATED_AT: new Date().toLocaleString('en-IN'), QR_CODE: qrCode };
      const filledBase64 = await fillDocxTemplateFromRow(docxRow, placeholders);

      const rep = getLastRenderReport();
      if (rep.missingTags.length) {
        reportClientError('Home', `autoPdf unresolved placeholders for ${recordId}`, undefined, { docType, genYear, recordId, missingTags: [...new Set(rep.missingTags)] });
      }

      const fileName = `${docType}-${placeholders[docNoKey]}.docx`;
      return { filledBase64, fileName, warning: qrCode ? '' : 'The QR in the PDF is blank.' };
    } catch (err) {
      reportClientError('Home', `autoPdf fill failed for ${recordId}`, err as Error, { docType, genYear, rowIndex });
      return { filledBase64: '', fileName: '', warning: 'The document could not be prepared: ' + (err as Error).message };
    }
  }

  async function submit(e: Event) {
    e.preventDefault();
    const isMoney = form['Contribution Type'] === '1';
    const isResell = isMoney && !!form['Is Resell'];
    const isUtrMode = isMoney && !isResell && (form['Payment Mode'] === 'UPI' || form['Payment Mode'] === 'Online');
    if (isResell) {
      if (!form.Detail.trim()) { alert("Resold item's name is required"); return; }
    } else {
      if (!form.Name) { alert('Please select a contributor'); return; }
      if (!isMoney && !form.Detail.trim()) { alert('Detail is required (what was given / what work was done)'); return; }
    }
    // audit P0-09: this used to be `if (!form.Amount)` only, so -500 / 1e21 /
    // '12.3456' were sent to the API. Same rules as the backend (lib/money.ts).
    if (isMoney || isResell) {
      const amount = checkMoney(form.Amount, 'Amount');
      if (!amount.ok) { alert(amount.message); return; }
    }
    saving = true;
    try {
      const payload: any = {
        Name: isResell ? '' : form.Name,
        'Payment Mode': isMoney ? form['Payment Mode'] : '',
        UTR: isUtrMode ? form.UTR : '',
        Date: form.Date,
        'Contribution Type': form['Contribution Type'],
        Amount: (isMoney || isResell) ? form.Amount : '',
        Detail: (isMoney && !isResell) ? '' : form.Detail,
        'Certificate Or Receipt': form['Contribution Type'] === '3' ? form['Certificate Or Receipt'] : '',
        'Is Resell': isResell ? 'TRUE' : 'FALSE'
      };
      let savedRowIndex: number;
      let genYear: any;
      const isNewEntry = !editing;
      if (editing) {
        genYear = editing.Year;
        savedRowIndex = editing.__rowIndex;
        await api.updateRecord('COLLECTIONS', editing.__rowIndex, { Year: editing.Year, 'Sl. No.': editing['Sl. No.'], ...payload, 'Created By': editing['Created By'] });
      } else {
        genYear = year === 'All' ? new Date().getFullYear() : year;
        const res: any = await api.saveRecord('COLLECTIONS', { Year: genYear, ...payload });
        savedRowIndex = res.rowIndex;
      }
      invalidate('home:');

      const docType = autoGenerateDocType(payload);
      const genPayload = { Year: genYear, ...payload };
      const warnings: string[] = [];

      let filled = { filledBase64: '', fileName: '' };
      if (docType && savedRowIndex) {
        savingStep = 'Preparing document...';
        const fillResult = await fillDocxForQueue(docType, savedRowIndex, genYear);
        filled = { filledBase64: fillResult.filledBase64 || '', fileName: fillResult.fileName || '' };
        if (fillResult.warning) warnings.push(fillResult.warning);
      }

      savingStep = 'Adding to the queue...';
      try {
        await api.enqueueCollectionJob({
          docType: docType || '',
          year: genYear,
          rowIndex: savedRowIndex,
          recordId: (docType && savedRowIndex) ? `${docType}-${genYear}-${savedRowIndex}` : '',
          isNewEntry,
          payload: genPayload,
          filledBase64: filled.filledBase64,
          fileName: filled.fileName
        });
        api.processCollectionQueue().catch(() => {});
        warnings.push('The PDF and WhatsApp message have been queued in the background — they will complete shortly.');
      } catch (err) {
        reportClientError('Home', 'enqueueCollectionJob failed — falling back to inline', err as Error, { docType, genYear, rowIndex: savedRowIndex });
        let fileLink = '';
        if (docType && savedRowIndex && filled.filledBase64) {
          try {
            const res: any = await api.convertDocxToPdf(docType, genYear, `${docType}-${genYear}-${savedRowIndex}`, filled.filledBase64, filled.fileName);
            fileLink = (res && res.publicLink) || '';
          } catch (e2) { warnings.push('PDF generation failed: ' + (e2 as Error).message); }
        }
        if (isNewEntry) {
          try {
            await api.queueCollectionMessages(genPayload, savedRowIndex, fileLink);
          } catch (e3) {
            warnings.push('The WhatsApp message could not be queued: ' + (e3 as Error).message);
          }
        }
      }

      postSaveWarning = warnings.join(' | ');
      queueBump = queueBump + 1;
      closeModal();
      view.refresh();
    } catch (err) {
      alert((err as Error).message);
    } finally {
      saving = false;
      savingStep = '';
    }
  }

  function closeModal() {
    showAdd = false;
    editing = null;
    form = BLANK();
  }

  function openEdit(r: any) {
    editing = r;
    form = {
      Name: r.Name, Amount: r.Amount, 'Payment Mode': r['Payment Mode'] || 'Cash', UTR: r.UTR || '',
      Date: r.Date || new Date().toISOString().slice(0, 10),
      'Contribution Type': (r['Contribution Type'] ?? '').toString() || '1', Detail: r.Detail || '',
      'Certificate Or Receipt': r['Certificate Or Receipt'] || 'Receipt',
      'Is Resell': r['Is Resell'] === 'TRUE' || r['Is Resell'] === true
    };
    showAdd = true;
  }

  async function remove(r: any) {
    if (!confirm('Delete this collection entry?')) return;
    try {
      await api.deleteRecord('COLLECTIONS', r.__rowIndex);
      invalidate('home:');
      view.refresh();
    } catch (err) {
      alert((err as Error).message);
    }
  }

  function historyTags(h: any): string[] {
    const tags: string[] = [];
    if (h.HasSamaan) tags.push('Material');
    if (h.HasKaam) tags.push('Service');
    return tags;
  }
</script>

{#if vs.loading}
  <div class="inline-spinner">Loading budget...</div>
{:else if vs.error}
  <div class="error-banner">{vs.error}</div>
{:else if !vs.data}
  <div class="inline-spinner">Loading budget...</div>
{:else}
  {@const data = vs.data}
  <div class="glass-card budget-card">
    <h2 style="margin-bottom:15px;">{year === 'All' ? 'Lifetime' : year} Budget Overview</h2>
    <div style="display:flex; justify-content:space-between; margin-bottom:10px;">
      <span>(+) Past Loan Returned</span><strong>{fmt(data.pastRet)}</strong>
    </div>
    <div style="display:flex; justify-content:space-between; margin-bottom:15px;">
      <span>(+) Collection</span><strong style="color:#34D399;">+{fmt(data.totCol)}</strong>
    </div>
    <div style="border-top:1px dashed #4B5563; padding-top:15px; display:flex; justify-content:space-between;">
      <strong>TOTAL BUDGET</strong><strong style="color:var(--primary-saffron); font-size:1.5rem;">{fmt(data.totBudget)}</strong>
    </div>
  </div>

  <div class="grid-2" style="margin-bottom:20px;">
    <div class="stat-box" style="border-color:var(--danger);">
      <div style="font-size:0.8rem; color:gray;">Total Expense</div>
      <div style="font-size:1.2rem; font-weight:bold; color:var(--danger);">{fmt(data.totExp)}</div>
    </div>
    <div class="stat-box" style="border-color:var(--success);">
      <div style="font-size:0.8rem; color:gray;">Net Surplus</div>
      <div style="font-size:1.2rem; font-weight:bold; color:var(--success);">{fmt(data.surplus)}</div>
    </div>
  </div>

  {#if postSaveWarning}
    <div style="background:#FEF3C7; color:#92400E; border-radius:8px; padding:10px 12px; font-size:0.85rem; margin-bottom:12px; display:flex; justify-content:space-between; gap:8px;">
      <span>⚠️ The entry was saved, but: {postSaveWarning}</span>
      <!-- svelte-ignore a11y_click_events_have_key_events -->
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <span style="cursor:pointer; font-weight:700;" onclick={() => (postSaveWarning = '')}>×</span>
    </div>
  {/if}

  <QueueStatus refreshKey={queueBump} />

  <h3 style="margin-bottom:15px;">Collections (Contribution)</h3>
  <input placeholder="Search Contribution Data..." style="margin-bottom:15px;" bind:value={search} />

  {#if data.hasMore}
    <div style="background:#EFF6FF; color:#1E40AF; border-radius:8px; padding:8px 12px; font-size:0.85rem; margin-bottom:12px;">
      Showing the {data.shownRows} most recent of {data.totalRows} contributions.
      The totals above cover all of them. Select a specific year to see its complete list.
    </div>
  {/if}
  <div class="glass-card">
    {#if filtered.length === 0}
      <div style="text-align:center; padding:20px;">No records found.</div>
    {/if}
    {#each visible as r (r.__rowIndex)}
      {@const isResellRow = r['Is Resell'] === 'TRUE' || r['Is Resell'] === true}
      {@const u = isResellRow ? null : (userMap[r.Name] || { Name: 'Unknown User', Village: '-' })}
      {@const ctype = (r['Contribution Type'] ?? '').toString() || '1'}
      <div class="data-row">
        <div>
          {#if isResellRow}
            <strong style="display:block;">
              ♻️ Resell: {r.Detail || '-'} {#if year === 'All'}<span style="color:var(--primary-saffron); font-size:0.75rem;">[{r.Year}]</span>{/if}
            </strong>
          {:else}
            <strong style="display:block;">{u!.Name} | {u!.Designation || '-'} {#if year === 'All'}<span style="color:var(--primary-saffron); font-size:0.75rem;">[{r.Year}]</span>{/if}</strong>
            <span style="font-size:0.8rem; color:var(--text-muted);">{u!["Father's Name"] || '-'} | {u!.Village || '-'}</span>
          {/if}
        </div>
        <div style="display:flex; flex-direction:column; align-items:flex-end; gap:4px;">
          {#if ctype === '1'}
            <strong style="color:var(--success);">+{fmt(r.Amount)}</strong>
          {:else}
            <span class="badge" style="background:#DBEAFE; color:#1E40AF;">
              {ctype === '2' ? 'Material' : 'Service'}{r['Certificate Or Receipt'] === 'Certificate' ? ' — Certificate' : ''}
            </span>
          {/if}
          {#if !isResellRow && r.Detail}<span style="font-size:0.75rem; color:var(--text-muted); max-width:180px; text-align:right;">{r.Detail}</span>{/if}
          {#if r['Payment Mode']}<span class="badge" style="background:#f3f4f6; color:#374151;">{r['Payment Mode']}{paymentModeHindiOf(r['Payment Mode']) ? ` (${paymentModeHindiOf(r['Payment Mode'])})` : ''}</span>{/if}
          {#if r.UTR}<span style="font-size:0.7rem; color:var(--text-muted);">UTR: {r.UTR}</span>{/if}
          <div style="display:flex; align-items:center; gap:6px;">
            <RowActions {role} disabled={!editable} onEdit={() => openEdit(r)} onDelete={() => remove(r)} />
          </div>
        </div>
      </div>
    {/each}
    {#if filtered.length > RENDER_CAP}
      <div style="text-align:center; padding:14px; color:var(--text-muted); font-size:0.85rem;">
        Showing {RENDER_CAP} of {filtered.length} matching rows — refine the search to narrow the list.
      </div>
    {/if}
  </div>

  {#if editable && canAddView(role, 'home')}
    <button class="fab" onclick={() => (showAdd = true)}><span class="material-icons-round">add</span></button>
  {/if}

  <Modal open={showAdd} onClose={closeModal}>
    <h3 style="margin-bottom:15px;">{editing ? 'Edit Collection' : 'Add Collection'}</h3>
    <form onsubmit={submit}>
      <div class="form-group">
        <label>Contribution Type</label>
        <select
          value={form['Contribution Type']}
          onchange={(e) => {
            const v = (e.currentTarget as HTMLSelectElement).value;
            form = { ...form, 'Contribution Type': v, 'Is Resell': v === '1' ? form['Is Resell'] : false };
          }}
        >
          <option value="1">Cash (Money)</option>
          <option value="2">Material (Item)</option>
          <option value="3">Service (Work)</option>
        </select>
      </div>

      {#if form['Contribution Type'] === '1'}
        <div class="form-group" style="display:flex; align-items:center; gap:8px;">
          <input
            type="checkbox"
            id="isResell"
            checked={!!form['Is Resell']}
            onchange={(e) => (form = { ...form, 'Is Resell': (e.currentTarget as HTMLInputElement).checked, Name: '' })}
            style="width:auto;"
          />
          <label for="isResell" style="margin:0;">This is an entry for a resold item (no contributor)</label>
        </div>
      {/if}

      {#if form['Contribution Type'] === '1' && form['Is Resell']}
        <div class="form-group">
          <label>Resold Item Name</label>
          <input value={form.Detail} oninput={(e) => (form = { ...form, Detail: (e.currentTarget as HTMLInputElement).value })} placeholder="e.g. Old utensils, clothes, etc." />
        </div>
      {:else}
        <div class="form-group">
          <label>Contributor</label>
          <SearchableSelect
            options={userOptions}
            value={form.Name}
            onChange={(id) => (form = { ...form, Name: id })}
            placeholder="Search name or village..."
            onAddNew={() => (showQuickAdd = true)}
          />
        </div>
      {/if}

      {#if form.Name && !form['Is Resell']}
        <div class="form-group" style="background:#f9fafb; border-radius:8px; padding:10px 12px;">
          <label style="margin-bottom:6px;">Last 5 Years Contribution</label>
          {#if historyLoading}<div style="font-size:0.85rem; color:var(--text-muted);">Loading...</div>{/if}
          {#if !historyLoading && (!history || history.length === 0)}<div style="font-size:0.85rem; color:var(--text-muted);">No prior contributions</div>{/if}
          {#if !historyLoading && history}
            {#each history as h (h.Year)}
              {@const tags = historyTags(h)}
              <div style="display:flex; justify-content:space-between; font-size:0.85rem; padding:3px 0;">
                <span>{h.Year}</span>
                <span>
                  {#if h.Amount > 0}<strong style="color:var(--success);">{fmt(h.Amount)}</strong>{/if}
                  {#if tags.length > 0}<span style="color:var(--text-muted);">{h.Amount > 0 ? ' + ' : ''}{tags.join(', ')}</span>{/if}
                </span>
              </div>
            {/each}
          {/if}
        </div>
      {/if}

      {#if form['Contribution Type'] === '1'}
        <div class="form-group">
          <label>Amount</label>
          <input type="number" min="0.01" step="0.01" value={form.Amount} oninput={(e) => (form = { ...form, Amount: (e.currentTarget as HTMLInputElement).value })} />
        </div>
      {:else}
        <div class="form-group">
          <label>{form['Contribution Type'] === '2' ? 'What was given (Item Detail)' : 'What work was done (Work Detail)'}</label>
          <textarea rows={2} value={form.Detail} oninput={(e) => (form = { ...form, Detail: (e.currentTarget as HTMLTextAreaElement).value })} style="width:100%; padding:8px; border-radius:8px; border:1px solid #ddd;"></textarea>
        </div>
      {/if}

      {#if form['Contribution Type'] === '3'}
        <div class="form-group">
          <label>Document Type</label>
          <select value={form['Certificate Or Receipt']} onchange={(e) => (form = { ...form, 'Certificate Or Receipt': (e.currentTarget as HTMLSelectElement).value })}>
            <option value="Receipt">Receipt</option>
            <option value="Certificate">Certificate</option>
          </select>
        </div>
      {/if}

      {#if form['Contribution Type'] === '1'}
        <div class="form-group">
          <label>Payment Mode</label>
          <select value={form['Payment Mode']} onchange={(e) => (form = { ...form, 'Payment Mode': (e.currentTarget as HTMLSelectElement).value })}>
            {#each paymentModeOptions as p (p['English Value'])}
              <option value={p['English Value']}>
                {p['English Value']}{p['Hindi Label'] ? ` (${p['Hindi Label']})` : ''}
              </option>
            {/each}
          </select>
        </div>
      {/if}

      {#if form['Contribution Type'] === '1' && (form['Payment Mode'] === 'UPI' || form['Payment Mode'] === 'Online')}
        <div class="form-group">
          <label>UTR / Transaction ID</label>
          <input value={form.UTR} oninput={(e) => (form = { ...form, UTR: (e.currentTarget as HTMLInputElement).value })} placeholder="UPI/Bank UTR number" />
        </div>
      {/if}

      <div class="form-group">
        <label>Date</label>
        <input type="date" value={form.Date} oninput={(e) => (form = { ...form, Date: (e.currentTarget as HTMLInputElement).value })} />
      </div>
      <button class="btn-submit" disabled={saving}>{saving ? (savingStep || 'Saving...') : 'Save'}</button>
    </form>
  </Modal>

  <QuickAddUser
    open={showQuickAdd}
    onClose={() => (showQuickAdd = false)}
    onCreated={(id) => { onUserCreated(); form = { ...form, Name: id }; }}
  />
{/if}
