// mgmt/frontend/src/views/PopupManagement.jsx
import { useEffect, useState } from 'react';
import { api, reportClientError } from '../api.js';
import { isTruthyFlag } from '../flags.js';
import { prepareImageForUpload } from '../imagePrep.js';
import Modal from '../components/Modal.jsx';
import PopupSlideshow from '../components/PopupSlideshow.jsx';
// Older rows may contain a Drive viewer-page URL or `uc?export=view` — neither
// renders in the browser. driveUrl.js converts them all to the lh3 CDN form.
import { driveImageUrl, driveImgOnError } from '../driveUrl.js';

const ROLES = ['Superadmin', 'Admin', 'Subadmin', 'Public'];
// durationMs = how long this slide stays on screen during auto-play (public
// portal + login popup). Kept in ms internally (matches the backend column and
// the API); the editor shows/edits it in whole SECONDS. Default 5000ms.
const DEFAULT_DURATION_MS = 5000;
const MIN_DURATION_MS = 1000;
const MAX_DURATION_MS = 60000;
const BLANK_SLIDE = { imageUrl: '', text: '', linkUrl: '', linkText: '', durationMs: DEFAULT_DURATION_MS };

// Clamp identically to the backend (normalizeDurationMs) so what the editor sends
// is exactly what gets stored and shown.
function clampDurationMs(ms) {
  const n = parseInt(ms, 10);
  if (!Number.isFinite(n) || n <= 0) return DEFAULT_DURATION_MS;
  if (n < MIN_DURATION_MS) return MIN_DURATION_MS;
  if (n > MAX_DURATION_MS) return MAX_DURATION_MS;
  return n;
}
// Each slide carries a stable client-side `_key` so React tracks it correctly
// across reordering (moveSlide) — array-index keys made the wrong slide's fields
// appear to jump on a move (audit L-20). The `_key` is UI-only and is stripped
// before saving.
let __slideKeySeq = 0;
const newSlide = (data) => ({ ...BLANK_SLIDE, ...(data || {}), _key: `sl_${Date.now()}_${__slideKeySeq++}` });

// `datetime-local` gives a bare wall-clock string like "2026-09-01T01:12" with NO
// timezone, and that used to be stored verbatim. The Worker then did
// `new Date(start_at) > now`, and a bare date-time is interpreted as LOCAL time —
// which inside a Worker means UTC. So an admin in IST picking 2:31 PM produced a
// window that actually opened at 2:31 PM UTC = 8:01 PM IST, i.e. 5.5 hours late.
// Converting to a real instant here (the browser DOES know the local zone) makes
// the stored value unambiguous.
function fromLocalInputValue(local) {
  if (!local) return '';
  const d = new Date(local); // parsed in the BROWSER's zone — this is the point
  return isNaN(d.getTime()) ? '' : d.toISOString();
}

// Legacy rows are '2026-08-22 14:31:00' (space, no zone) and are read as UTC —
// which is how the Worker has always compared them. The zone is appended BEFORE
// parsing, because Chrome would otherwise happily read the string as IST wall time
// and show the admin a window 5.5h away from the one the server actually enforces.
// Keep in step with parseStoredDate in mgmt/backend/src/popups.js.
function normalizeStamp(raw) {
  const hasZone = /([zZ]|[+-]\d{2}:?\d{2})$/.test(raw);
  let d = new Date(raw.replace(' ', 'T') + (hasZone ? '' : 'Z'));
  if (!isNaN(d.getTime())) return d;
  d = new Date(raw);
  return isNaN(d.getTime()) ? null : d;
}

function toLocalInputValue(iso) {
  if (!iso) return '';
  const d = normalizeStamp(iso.toString().trim());
  if (!d) return '';
  const pad = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

// Same normalization for display, so the list never shows "Invalid Date".
function fmtStamp(v) {
  if (!v) return null;
  const d = normalizeStamp(v.toString().trim());
  return d ? d.toLocaleString('en-IN') : null;
}

// Everything the DB can hand back is nullable, and the migrated slide row has
// text/link_url/link_text = NULL. Coercing here (as well as on the backend) means
// no `.trim()` in this file can ever hit null again.
const str = (v) => (v === undefined || v === null ? '' : v.toString());

// NOTE: there used to be a `fileToBase64()` here that sent the file as-is. It was
// replaced by `prepareImageForUpload()` in `imagePrep.js` — the reason is in the
// comment there (payload size + Worker CPU + iPhone HEIC).

// A button that looks like a link. The `btn-link` class does NOT exist in styles.css,
// so we use an inline style — otherwise it would show the default grey browser button.
const linkBtnStyle = {
  background: 'none', border: 'none', padding: 0, font: 'inherit',
  color: 'var(--primary-saffron)', textDecoration: 'underline', cursor: 'pointer',
};

export default function PopupManagement() {
  const [popups, setPopups] = useState(null);
  const [error, setError] = useState('');
  const [editingId, setEditingId] = useState(null); // null = not editing, 'new' = creating
  const [form, setForm] = useState({ title: '', roles: [...ROLES], active: true, startAt: '', endAt: '' });
  const [slides, setSlides] = useState([newSlide()]);
  const [saving, setSaving] = useState(false);
  const [uploadingSlide, setUploadingSlide] = useState(null);
  const [preview, setPreview] = useState(null);       // "Preview as Public" result
  const [previewLoading, setPreviewLoading] = useState(false);
  const [showLivePreview, setShowLivePreview] = useState(false); // visual slideshow preview of the slides being edited

  const refresh = () => {
    api.getPopups().then(setPopups).catch(err => setError(err.message));
  };
  useEffect(() => { refresh(); }, []);

  const startNew = () => {
    setEditingId('new');
    setForm({ title: '', roles: [...ROLES], active: true, startAt: '', endAt: '' });
    setSlides([newSlide()]);
  };

  const startEdit = async (popupId) => {
    setError('');
    try {
      const { popup, slides: existingSlides } = await api.getPopupWithSlides(popupId);
      setEditingId(popupId);
      setForm({
        title: str(popup.title),
        roles: (popup.roles || '').split(',').map(r => r.trim()).filter(Boolean),
        active: isTruthyFlag(popup.active),
        startAt: toLocalInputValue(popup.start_at),
        endAt: toLocalInputValue(popup.end_at),
      });
      // str() everywhere: a NULL text/link from the DB used to arrive as `null`,
      // and save()'s `s.text.trim()` then threw a TypeError OUTSIDE its try/catch —
      // so the Save button silently did nothing at all.
      setSlides(existingSlides.length
        ? existingSlides.map(s => newSlide({ imageUrl: str(s.image_url), text: str(s.text), linkUrl: str(s.link_url), linkText: str(s.link_text), durationMs: clampDurationMs(s.duration_ms) }))
        : [newSlide()]);
    } catch (err) {
      setError(err.message);
    }
  };

  const cancelEdit = () => { setEditingId(null); };

  const toggleRole = (role) => {
    setForm(f => ({ ...f, roles: f.roles.includes(role) ? f.roles.filter(r => r !== role) : [...f.roles, role] }));
  };

  const addSlide = () => setSlides(s => [...s, newSlide()]);
  const removeSlide = (i) => setSlides(s => s.filter((_, idx) => idx !== i));
  // Slide order decides the display sequence but there was no way to change it
  // without deleting and re-adding every slide.
  const moveSlide = (i, dir) => setSlides(s => {
    const j = i + dir;
    if (j < 0 || j >= s.length) return s;
    const copy = [...s];
    [copy[i], copy[j]] = [copy[j], copy[i]];
    return copy;
  });
  const updateSlide = (i, patch) => setSlides(s => s.map((sl, idx) => idx === i ? { ...sl, ...patch } : sl));

  const uploadSlideImage = async (i, file) => {
    setUploadingSlide(i);
    setError('');
    // Clear the previous attempt's error/flag, otherwise the old message stays
    // stuck on the new upload too.
    updateSlide(i, { imageError: '', imageBroken: false });
    try {
      // The file used to be sent as-is. A phone photo is 3-8 MB (+33% as base64),
      // and the Worker's decode burnt over half a second of CPU on it — large
      // photos failed to upload. prepareImageForUpload downscales to 1600px + JPEG
      // right in the browser (~200-400 KB), and also converts iOS HEIC photos to
      // JPEG.
      const prepped = await prepareImageForUpload(file);
      const res = await api.uploadPopupImage(prepped.base64, prepped.fileName, prepped.mimeType);
      // `res.url` is the Drive VIEWER PAGE (…/file/d/<id>/view) — an HTML document,
      // not an image, so <img src> rendered nothing. `imageUrl`/`directUrl` is the
      // actual image (…/uc?export=view&id=<id>). Every popup image uploaded through
      // this screen was broken in the editor, at login AND on the public portal.
      const imageUrl = res.imageUrl || res.directUrl || res.url;
      if (!imageUrl) throw new Error('The server did not return an image URL.');
      updateSlide(i, { imageUrl, imageError: '', imageBroken: false });
    } catch (err) {
      // `alert()` is sometimes suppressed on mobile, and then the admin thinks
      // "nothing happened at all". So the error is shown inside the slide as well.
      updateSlide(i, { imageError: err.message || 'Upload failed.' });
      setError(`Slide ${i + 1} image upload failed: ${err.message}`);
      reportClientError('PopupManagement', 'Popup image upload failed', err, {
        slide: i, fileName: file && file.name, fileType: file && file.type, fileSize: file && file.size,
      });
    } finally {
      setUploadingSlide(null);
    }
  };

  const save = async () => {
    // Validation moved INSIDE the try. It used to sit outside, so a TypeError from
    // `s.text.trim()` on a NULL text escaped as an unhandled rejection and the
    // Save button did nothing — no alert, no banner, no clue.
    setSaving(true);
    setError('');
    try {
      const title = str(form.title).trim();
      if (!title) throw new Error('Please enter a title');

      // Send only the 4 persisted fields. `imageError`/`imageBroken` are UI-only
      // state — sending them in the request is wasted payload.
      const usable = slides
        .filter(s => str(s.imageUrl) || str(s.text).trim())
        .map(s => ({
          imageUrl: str(s.imageUrl),
          text: str(s.text),
          linkUrl: str(s.linkUrl),
          linkText: str(s.linkText),
          durationMs: clampDurationMs(s.durationMs),
        }));
      if (!usable.length) throw new Error('At least one slide must have an image or text');
      if (!form.roles.length) throw new Error('Select at least one role, otherwise the popup will not be shown to anyone.');

      const popupId = editingId === 'new' ? undefined : editingId;
      const res = await api.savePopup(
        popupId, title, form.roles, form.active,
        // Converted to a real instant so the window isn't 5.5 h off (see
        // fromLocalInputValue).
        fromLocalInputValue(form.startAt), fromLocalInputValue(form.endAt)
      );
      const finalId = popupId || res.popup_id;
      await api.savePopupSlides(finalId, usable);
      setEditingId(null);
      refresh();
    } catch (err) {
      setError(err.message);
      reportClientError('PopupManagement', 'Popup save failed', err, { editingId });
    } finally {
      setSaving(false);
    }
  };

  const runPreview = async () => {
    setPreviewLoading(true);
    setError('');
    try {
      setPreview(await api.previewPublicPopups());
    } catch (err) {
      setError(err.message);
    } finally {
      setPreviewLoading(false);
    }
  };

  const remove = async (popupId) => {
    if (!confirm('Delete this popup? All its slides will be deleted as well.')) return;
    try {
      await api.deletePopup(popupId);
      refresh();
    } catch (err) {
      alert(err.message);
    }
  };

  if (editingId) {
    return (
      <>
        <h2 style={{ marginBottom: 15 }}>{editingId === 'new' ? 'New Popup' : 'Edit Popup'}</h2>
        {error && <div className="error-banner">{error}</div>}

        <div className="glass-card" style={{ padding: 15, marginBottom: 15 }}>
          <div className="form-group">
            <label>Title (for Superadmin reference only, not shown to viewers)</label>
            <input value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} />
          </div>

          <div className="form-group">
            <label>Visible to which roles</label>
            <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap' }}>
              {ROLES.map(role => (
                <label key={role} style={{ display: 'flex', alignItems: 'center', gap: 6, cursor: 'pointer' }}>
                  <input type="checkbox" checked={form.roles.includes(role)} onChange={() => toggleRole(role)} />
                  {role}
                </label>
              ))}
            </div>
            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: 4 }}>
              "Public" shows this popup on the public transparency portal (chhathmanagment) on every page load — separate from the Superadmin/Admin/Subadmin roles, which only apply inside this mgmt portal.
            </div>
          </div>

          <label style={{ display: 'flex', alignItems: 'center', gap: 8, margin: '10px 0', cursor: 'pointer' }}>
            <input type="checkbox" checked={form.active} onChange={e => setForm({ ...form, active: e.target.checked })} />
            Active
          </label>

          <div className="form-group">
            <label>Start Date &amp; Time</label>
            <input type="datetime-local" value={form.startAt} onChange={e => setForm({ ...form, startAt: e.target.value })} />
          </div>
          <div className="form-group">
            <label>End Date &amp; Time</label>
            <input type="datetime-local" value={form.endAt} onChange={e => setForm({ ...form, endAt: e.target.value })} />
            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: 4 }}>
              You can leave both empty — the popup will then run with no time limit.
              The time is in your phone's local time ({Intl.DateTimeFormat().resolvedOptions().timeZone}).
            </div>
          </div>
        </div>

        <div className="glass-card" style={{ padding: 15, marginBottom: 15 }}>
          <strong>Slides</strong>
          {slides.map((slide, i) => (
            <div key={slide._key ?? i} style={{ background: '#f9fafb', borderRadius: 8, padding: 12, marginTop: 10 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
                <strong style={{ fontSize: '0.85rem' }}>Slide {i + 1}</strong>
                <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                  {slides.length > 1 && (
                    <>
                      <span
                        className="material-icons-round"
                        title="Upar le jaayein"
                        style={{ cursor: i === 0 ? 'not-allowed' : 'pointer', opacity: i === 0 ? 0.3 : 1, fontSize: '1.1rem' }}
                        onClick={() => i > 0 && moveSlide(i, -1)}
                      >arrow_upward</span>
                      <span
                        className="material-icons-round"
                        title="Neeche le jaayein"
                        style={{ cursor: i === slides.length - 1 ? 'not-allowed' : 'pointer', opacity: i === slides.length - 1 ? 0.3 : 1, fontSize: '1.1rem' }}
                        onClick={() => i < slides.length - 1 && moveSlide(i, 1)}
                      >arrow_downward</span>
                      <span className="material-icons-round" title="Delete" style={{ cursor: 'pointer', color: 'var(--danger)', fontSize: '1.1rem' }} onClick={() => removeSlide(i)}>delete</span>
                    </>
                  )}
                </div>
              </div>

              <div className="form-group">
                <label style={{ fontSize: '0.8rem' }}>Image (optional)</label>
                <input type="file" accept="image/jpeg,image/png,image/gif,image/webp,image/heic,image/heif" onChange={e => e.target.files[0] && uploadSlideImage(i, e.target.files[0])} />
                {uploadingSlide === i && <div className="inline-spinner">Uploading...</div>}

                {/* The upload error is shown right here — we don't rely on alert() alone. */}
                {slide.imageError && (
                  <div style={{ marginTop: 8, padding: '8px 10px', borderRadius: 8, background: '#fdecea', color: 'var(--danger)', fontSize: '0.8rem' }}>
                    {slide.imageError}
                  </div>
                )}

                {slide.imageUrl && !slide.imageBroken && (
                  <img
                    src={driveImageUrl(slide.imageUrl)}
                    alt=""
                    style={{ maxWidth: '100%', maxHeight: 150, marginTop: 8, borderRadius: 8 }}
                    // This used to be `display='none'` — if the image failed to
                    // load it disappeared SILENTLY, so the admin had no idea whether
                    // the upload succeeded. Now it tries the fallback endpoint first,
                    // then shows a clear placeholder.
                    onError={(e) => {
                      const img = e.currentTarget;
                      if (img.dataset.driveFallbackTried !== '1') {
                        driveImgOnError(slide.imageUrl)(e);
                        if (img.dataset.driveFallbackTried === '1') return;
                      }
                      updateSlide(i, { imageBroken: true });
                    }}
                    onLoad={() => slide.imageBroken && updateSlide(i, { imageBroken: false })}
                  />
                )}

                {slide.imageUrl && slide.imageBroken && (
                  <div style={{ marginTop: 8, padding: 10, borderRadius: 8, border: '1px dashed var(--danger)', fontSize: '0.8rem' }}>
                    <div style={{ fontWeight: 600, color: 'var(--danger)', marginBottom: 4 }}>
                      The image failed to load — it will not show on the public portal either
                    </div>
                    <div style={{ color: 'var(--text-muted)', wordBreak: 'break-all', marginBottom: 6 }}>{slide.imageUrl}</div>
                    <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                      <a href={slide.imageUrl} target="_blank" rel="noreferrer">Open link</a>
                      <button type="button" style={linkBtnStyle} onClick={() => updateSlide(i, { imageBroken: false })}>Try again</button>
                      <button type="button" style={linkBtnStyle} onClick={() => updateSlide(i, { imageUrl: '', imageBroken: false, imageError: '' })}>Remove image</button>
                    </div>
                  </div>
                )}
              </div>

              <div className="form-group">
                <label style={{ fontSize: '0.8rem' }}>Text (optional)</label>
                <textarea rows={3} value={slide.text} onChange={e => updateSlide(i, { text: e.target.value })} style={{ width: '100%', padding: 8, borderRadius: 8, border: '1px solid #ddd' }} />
              </div>

              <div className="form-group">
                <label style={{ fontSize: '0.8rem' }}>Link URL (optional)</label>
                <input value={slide.linkUrl} onChange={e => updateSlide(i, { linkUrl: e.target.value })} placeholder="https://..." />
              </div>
              {slide.linkUrl && (
                <div className="form-group">
                  <label style={{ fontSize: '0.8rem' }}>Link Text</label>
                  <input value={slide.linkText} onChange={e => updateSlide(i, { linkText: e.target.value })} placeholder="e.g. More Info" />
                </div>
              )}

              {/* Per-slide auto-play duration. Edited in whole seconds, stored in
                  ms. Only meaningful when the popup has 2+ slides (auto-play does
                  not run for a single slide), so the hint says so. */}
              <div className="form-group">
                <label style={{ fontSize: '0.8rem' }}>Auto-play duration (seconds)</label>
                <input
                  type="number"
                  min={MIN_DURATION_MS / 1000}
                  max={MAX_DURATION_MS / 1000}
                  step={1}
                  value={Math.round((slide.durationMs ?? DEFAULT_DURATION_MS) / 1000)}
                  onChange={e => {
                    // Keep the raw seconds while typing; clamp to ms on blur so an
                    // empty/partial value doesn't fight the user mid-edit.
                    const secs = parseInt(e.target.value, 10);
                    updateSlide(i, { durationMs: Number.isFinite(secs) ? secs * 1000 : '' });
                  }}
                  onBlur={() => updateSlide(i, { durationMs: clampDurationMs(slide.durationMs) })}
                  style={{ maxWidth: 120 }}
                />
                <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)', marginTop: 4 }}>
                  {slides.length > 1
                    ? `Is slide ke baad agli slide par jaane se pehle itni der rukega (${MIN_DURATION_MS / 1000}-${MAX_DURATION_MS / 1000}s). Aakhri slide ke baad wapas pehli par loop hota hai.`
                    : `Auto-play sirf tab chalta hai jab 2 ya zyada slides hon — abhi ek hi slide hai.`}
                </div>
              </div>
            </div>
          ))}
          <button type="button" className="btn-submit" style={{ width: 'auto', marginTop: 10, background: '#e5e7eb', color: '#111' }} onClick={addSlide}>
            + Add Slide
          </button>
        </div>

        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
          <button className="btn-submit" style={{ width: 'auto' }} onClick={save} disabled={saving}>{saving ? 'Saving...' : 'Save'}</button>
          <button
            type="button" className="btn-submit"
            style={{ width: 'auto', background: '#111827', color: '#fff' }}
            onClick={() => setShowLivePreview(true)}
          >👁 Live Preview</button>
          <button type="button" className="btn-submit" style={{ width: 'auto', background: '#e5e7eb', color: '#111' }} onClick={cancelEdit}>Cancel</button>
        </div>

        {/* Visual live preview — renders the slides EXACTLY as the public portal
            will (auto-play, loop, pause-on-hover), using the unsaved edits so the
            author sees the real thing before saving. */}
        {showLivePreview && (
          <Modal open onClose={() => setShowLivePreview(false)}>
            <h3 style={{ marginTop: 0, marginBottom: 6 }}>Live Preview</h3>
            <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: 0, marginBottom: 14 }}>
              Bilkul waisa hi jaisa public portal par dikhega — auto-play + loop chal raha hai; mouse le jaane par ruk jaata hai.
            </p>
            <PopupSlideshow
              slides={slides.filter(s => (s.imageUrl || (s.text || '').trim()))}
            />
          </Modal>
        )}
      </>
    );
  }

  return (
    <>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 8, flexWrap: 'wrap', marginBottom: 10 }}>
        <h2 style={{ margin: 0 }}>Popup Management</h2>
        <button
          type="button" className="btn-submit"
          style={{ width: 'auto', padding: '6px 12px', fontSize: '0.8rem', background: '#e5e7eb', color: '#111' }}
          onClick={runPreview} disabled={previewLoading}
        >
          {previewLoading ? 'Checking...' : '👁 Preview as Public'}
        </button>
      </div>
      {/* Popups are NOT year-scoped, but this screen sits under the app's global
          year selector, which made it look as though they were. */}
      <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginBottom: 12 }}>
        Popups are independent of the year — the year selector above does not apply to them.
      </p>
      {error && <div className="error-banner">{error}</div>}

      {preview && (
        <div className="glass-card" style={{ padding: 15, marginBottom: 15 }}>
          <strong style={{ fontSize: '0.9rem' }}>What will show on the public portal right now</strong>
          {preview.shown.length === 0 ? (
            <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', margin: '8px 0 0' }}>
              Nothing. To appear on the public portal, a popup must have the <strong>Public</strong> role,
              be Active, fall within its date window, and have at least 1 slide.
            </p>
          ) : (
            <p style={{ fontSize: '0.8rem', margin: '8px 0 0' }}>
              ✅ <strong>{preview.shown[0].title}</strong> ({preview.shown[0].slides.length} slide{preview.shown[0].slides.length === 1 ? '' : 's'})
            </p>
          )}
          {preview.alsoEligibleButNotShown.length > 0 && (
            <div style={{ background: '#FEF3C7', color: '#92400E', borderRadius: 6, padding: '6px 10px', fontSize: '0.75rem', marginTop: 8 }}>
              ⚠️ The public portal shows only the <strong>first</strong> popup at a time. These are eligible but
              will not show: {preview.alsoEligibleButNotShown.map(x => x.title).join(', ')}. Set their start/end
              times to different windows.
            </div>
          )}
          {preview.droppedNoSlides.length > 0 && (
            <div style={{ background: '#FEE2E2', color: '#991B1B', borderRadius: 6, padding: '6px 10px', fontSize: '0.75rem', marginTop: 8 }}>
              ⚠️ Dropped because they have no slides: {preview.droppedNoSlides.map(x => x.title).join(', ')}
            </div>
          )}
          <button
            type="button" className="btn-submit"
            style={{ width: 'auto', marginTop: 10, padding: '4px 10px', fontSize: '0.75rem', background: '#e5e7eb', color: '#111' }}
            onClick={() => setPreview(null)}
          >Close</button>
        </div>
      )}

      {!popups && <div className="inline-spinner">Loading...</div>}
      {popups && popups.length === 0 && <div className="glass-card" style={{ textAlign: 'center', padding: 20 }}>No popups have been created yet.</div>}

      {(popups || []).map(p => {
        const isActive = isTruthyFlag(p.active);
        const noSlides = p.slide_count === 0;
        const start = fmtStamp(p.start_at);
        const end = fmtStamp(p.end_at);
        const now = Date.now();
        const notYet = p.start_at && new Date(p.start_at).getTime() > now;
        const over = p.end_at && new Date(p.end_at).getTime() < now;
        // "Active" only means the flag is on. Whether it is actually being SHOWN
        // also depends on the date window and on having at least one slide — the
        // badge used to imply all three, which is how a popup could read "Active"
        // and still never appear anywhere.
        const liveNow = isActive && !noSlides && !notYet && !over;
        return (
          <div className="glass-card" key={p.popup_id} style={{ padding: 15, marginBottom: 10 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 8, flexWrap: 'wrap' }}>
              <div>
                <strong>{p.title}</strong>
                <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>{p.roles || 'All roles'}</div>
                <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                  {start || 'No start'} — {end || 'No end'}
                </div>
                <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                  {p.slide_count} slide{p.slide_count === 1 ? '' : 's'}
                </div>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 4, alignItems: 'flex-end' }}>
                <span className={`badge ${isActive ? 'badge-ok' : 'badge-warn'}`}>{isActive ? 'Active' : 'Inactive'}</span>
                {liveNow && <span className="badge badge-ok" style={{ fontSize: '0.65rem' }}>Showing now</span>}
              </div>
            </div>

            {isActive && noSlides && (
              <div style={{ background: '#FEE2E2', color: '#991B1B', borderRadius: 6, padding: '6px 10px', fontSize: '0.75rem', marginTop: 8 }}>
                ⚠️ This popup has no slides — it will <strong>not</strong> be shown to anyone. Edit it to add a slide.
              </div>
            )}
            {isActive && notYet && (
              <div style={{ background: '#FEF3C7', color: '#92400E', borderRadius: 6, padding: '6px 10px', fontSize: '0.75rem', marginTop: 8 }}>
                ⏳ The start time has not arrived yet ({start}) — it will not show until then.
              </div>
            )}
            {isActive && over && (
              <div style={{ background: '#FEF3C7', color: '#92400E', borderRadius: 6, padding: '6px 10px', fontSize: '0.75rem', marginTop: 8 }}>
                ⌛ The end time has passed ({end}) — it will no longer show.
              </div>
            )}
            <div className="row-actions" style={{ marginTop: 10 }}>
              <button type="button" className="icon-btn" title="Edit" onClick={() => startEdit(p.popup_id)}>
                <span className="material-icons-round" style={{ fontSize: 16 }}>edit</span>
              </button>
              <button type="button" className="icon-btn icon-danger" title="Delete" onClick={() => remove(p.popup_id)}>
                <span className="material-icons-round" style={{ fontSize: 16 }}>delete</span>
              </button>
            </div>
          </div>
        );
      })}

      <button className="fab" onClick={startNew}><span className="material-icons-round">add</span></button>
    </>
  );
}

// mgmt/frontend-svelte/src/lib/views/PopupManagement.svelte
<script lang="ts">
  // Ported from React views/PopupManagement.jsx — create/edit popups (title,
  // roles, active window, ordered image/text/link slides with upload) + a live
  // preview and a "preview as public" check. List view with status warnings.
  import { api, reportClientError } from '$lib/api';
  import { isTruthyFlag } from '$lib/flags';
  import { prepareImageForUpload } from '$lib/imagePrep';
  import Modal from '$lib/components/Modal.svelte';
  import PopupSlideshow from '$lib/components/PopupSlideshow.svelte';
  import { driveImageUrl, driveImgOnError } from '$lib/driveUrl';

  const ROLES = ['Superadmin', 'Admin', 'Subadmin', 'Public'];
  const DEFAULT_DURATION_MS = 5000;
  const MIN_DURATION_MS = 1000;
  const MAX_DURATION_MS = 60000;
  const BLANK_SLIDE = { imageUrl: '', text: '', linkUrl: '', linkText: '', durationMs: DEFAULT_DURATION_MS };

  function clampDurationMs(ms: unknown): number {
    const n = parseInt(ms as string, 10);
    if (!Number.isFinite(n) || n <= 0) return DEFAULT_DURATION_MS;
    if (n < MIN_DURATION_MS) return MIN_DURATION_MS;
    if (n > MAX_DURATION_MS) return MAX_DURATION_MS;
    return n;
  }
  let __slideKeySeq = 0;
  const newSlide = (data?: any) => ({ ...BLANK_SLIDE, ...(data || {}), _key: `sl_${Date.now()}_${__slideKeySeq++}` });

  function fromLocalInputValue(local: string): string {
    if (!local) return '';
    const d = new Date(local);
    return isNaN(d.getTime()) ? '' : d.toISOString();
  }

  function normalizeStamp(raw: string): Date | null {
    const hasZone = /([zZ]|[+-]\d{2}:?\d{2})$/.test(raw);
    let d = new Date(raw.replace(' ', 'T') + (hasZone ? '' : 'Z'));
    if (!isNaN(d.getTime())) return d;
    d = new Date(raw);
    return isNaN(d.getTime()) ? null : d;
  }

  function toLocalInputValue(iso: unknown): string {
    if (!iso) return '';
    const d = normalizeStamp(iso.toString().trim());
    if (!d) return '';
    const pad = (n: number) => String(n).padStart(2, '0');
    return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
  }

  function fmtStamp(v: unknown): string | null {
    if (!v) return null;
    const d = normalizeStamp(v.toString().trim());
    return d ? d.toLocaleString('en-IN') : null;
  }

  const str = (v: unknown) => (v === undefined || v === null ? '' : v.toString());

  const linkBtnStyle = 'background:none; border:none; padding:0; font:inherit; color:var(--primary-saffron); text-decoration:underline; cursor:pointer;';

  let popups = $state<any[] | null>(null);
  let error = $state('');
  let editingId = $state<string | null>(null);
  let form = $state<any>({ title: '', roles: [...ROLES], active: true, startAt: '', endAt: '' });
  let slides = $state<any[]>([newSlide()]);
  let saving = $state(false);
  let uploadingSlide = $state<number | null>(null);
  let preview = $state<any>(null);
  let previewLoading = $state(false);
  let showLivePreview = $state(false);

  function refresh() {
    api.getPopups().then((p: any) => (popups = p)).catch((err: Error) => (error = err.message));
  }
  let loaded = false;
  $effect(() => {
    if (loaded) return;
    loaded = true;
    refresh();
  });

  function startNew() {
    editingId = 'new';
    form = { title: '', roles: [...ROLES], active: true, startAt: '', endAt: '' };
    slides = [newSlide()];
  }

  async function startEdit(popupId: string) {
    error = '';
    try {
      const { popup, slides: existingSlides }: any = await api.getPopupWithSlides(popupId);
      editingId = popupId;
      form = {
        title: str(popup.title),
        roles: (popup.roles || '').split(',').map((r: string) => r.trim()).filter(Boolean),
        active: isTruthyFlag(popup.active),
        startAt: toLocalInputValue(popup.start_at),
        endAt: toLocalInputValue(popup.end_at)
      };
      slides = existingSlides.length
        ? existingSlides.map((s: any) => newSlide({ imageUrl: str(s.image_url), text: str(s.text), linkUrl: str(s.link_url), linkText: str(s.link_text), durationMs: clampDurationMs(s.duration_ms) }))
        : [newSlide()];
    } catch (err) {
      error = (err as Error).message;
    }
  }

  function cancelEdit() { editingId = null; }

  function toggleRole(role: string) {
    form = { ...form, roles: form.roles.includes(role) ? form.roles.filter((r: string) => r !== role) : [...form.roles, role] };
  }

  function addSlide() { slides = [...slides, newSlide()]; }
  function removeSlide(i: number) { slides = slides.filter((_, idx) => idx !== i); }
  function moveSlide(i: number, dir: number) {
    const j = i + dir;
    if (j < 0 || j >= slides.length) return;
    const copy = [...slides];
    [copy[i], copy[j]] = [copy[j], copy[i]];
    slides = copy;
  }
  function updateSlide(i: number, patch: any) {
    slides = slides.map((sl, idx) => (idx === i ? { ...sl, ...patch } : sl));
  }

  async function uploadSlideImage(i: number, file: File) {
    uploadingSlide = i;
    error = '';
    updateSlide(i, { imageError: '', imageBroken: false });
    try {
      const prepped = await prepareImageForUpload(file);
      const res: any = await api.uploadPopupImage(prepped.base64, prepped.fileName, prepped.mimeType);
      const imageUrl = res.imageUrl || res.directUrl || res.url;
      if (!imageUrl) throw new Error('The server did not return an image URL.');
      updateSlide(i, { imageUrl, imageError: '', imageBroken: false });
    } catch (err) {
      updateSlide(i, { imageError: (err as Error).message || 'Upload failed.' });
      error = `Slide ${i + 1} image upload failed: ${(err as Error).message}`;
      reportClientError('PopupManagement', 'Popup image upload failed', err as Error, {
        slide: i, fileName: file && file.name, fileType: file && file.type, fileSize: file && file.size
      });
    } finally {
      uploadingSlide = null;
    }
  }

  async function save() {
    saving = true;
    error = '';
    try {
      const title = str(form.title).trim();
      if (!title) throw new Error('Please enter a title');

      const usable = slides
        .filter((s) => str(s.imageUrl) || str(s.text).trim())
        .map((s) => ({
          imageUrl: str(s.imageUrl),
          text: str(s.text),
          linkUrl: str(s.linkUrl),
          linkText: str(s.linkText),
          durationMs: clampDurationMs(s.durationMs)
        }));
      if (!usable.length) throw new Error('At least one slide must have an image or text');
      if (!form.roles.length) throw new Error('Select at least one role, otherwise the popup will not be shown to anyone.');

      const popupId = editingId === 'new' ? undefined : (editingId ?? undefined);
      const res: any = await api.savePopup(
        popupId, title, form.roles, form.active,
        fromLocalInputValue(form.startAt), fromLocalInputValue(form.endAt)
      );
      const finalId = popupId || res.popup_id;
      await api.savePopupSlides(finalId, usable);
      editingId = null;
      refresh();
    } catch (err) {
      error = (err as Error).message;
      reportClientError('PopupManagement', 'Popup save failed', err as Error, { editingId });
    } finally {
      saving = false;
    }
  }

  async function runPreview() {
    previewLoading = true;
    error = '';
    try {
      preview = await api.previewPublicPopups();
    } catch (err) {
      error = (err as Error).message;
    } finally {
      previewLoading = false;
    }
  }

  async function remove(popupId: string) {
    if (!confirm('Delete this popup? All its slides will be deleted as well.')) return;
    try {
      await api.deletePopup(popupId);
      refresh();
    } catch (err) {
      alert((err as Error).message);
    }
  }

  const localTz = typeof Intl !== 'undefined' ? Intl.DateTimeFormat().resolvedOptions().timeZone : '';
  let livePreviewSlides = $derived(slides.filter((s) => s.imageUrl || (s.text || '').trim()));
</script>

{#if editingId}
  <h2 style="margin-bottom:15px;">{editingId === 'new' ? 'New Popup' : 'Edit Popup'}</h2>
  {#if error}<div class="error-banner">{error}</div>{/if}

  <div class="glass-card" style="padding:15px; margin-bottom:15px;">
    <div class="form-group">
      <label>Title (for Superadmin reference only, not shown to viewers)</label>
      <input value={form.title} oninput={(e) => (form = { ...form, title: (e.currentTarget as HTMLInputElement).value })} />
    </div>

    <div class="form-group">
      <label>Visible to which roles</label>
      <div style="display:flex; gap:12px; flex-wrap:wrap;">
        {#each ROLES as role (role)}
          <label style="display:flex; align-items:center; gap:6px; cursor:pointer;">
            <input type="checkbox" checked={form.roles.includes(role)} onchange={() => toggleRole(role)} />
            {role}
          </label>
        {/each}
      </div>
      <div style="font-size:0.75rem; color:var(--text-muted); margin-top:4px;">
        "Public" shows this popup on the public transparency portal (chhathmanagment) on every page load — separate from the Superadmin/Admin/Subadmin roles, which only apply inside this mgmt portal.
      </div>
    </div>

    <label style="display:flex; align-items:center; gap:8px; margin:10px 0; cursor:pointer;">
      <input type="checkbox" checked={form.active} onchange={(e) => (form = { ...form, active: (e.currentTarget as HTMLInputElement).checked })} />
      Active
    </label>

    <div class="form-group">
      <label>Start Date &amp; Time</label>
      <input type="datetime-local" value={form.startAt} oninput={(e) => (form = { ...form, startAt: (e.currentTarget as HTMLInputElement).value })} />
    </div>
    <div class="form-group">
      <label>End Date &amp; Time</label>
      <input type="datetime-local" value={form.endAt} oninput={(e) => (form = { ...form, endAt: (e.currentTarget as HTMLInputElement).value })} />
      <div style="font-size:0.75rem; color:var(--text-muted); margin-top:4px;">
        You can leave both empty — the popup will then run with no time limit.
        The time is in your phone's local time ({localTz}).
      </div>
    </div>
  </div>

  <div class="glass-card" style="padding:15px; margin-bottom:15px;">
    <strong>Slides</strong>
    {#each slides as slide, i (slide._key ?? i)}
      <div style="background:#f9fafb; border-radius:8px; padding:12px; margin-top:10px;">
        <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:8px;">
          <strong style="font-size:0.85rem;">Slide {i + 1}</strong>
          <div style="display:flex; align-items:center; gap:10px;">
            {#if slides.length > 1}
              <!-- svelte-ignore a11y_click_events_have_key_events -->
              <!-- svelte-ignore a11y_no_static_element_interactions -->
              <span class="material-icons-round" title="Upar le jaayein" style="cursor:{i === 0 ? 'not-allowed' : 'pointer'}; opacity:{i === 0 ? 0.3 : 1}; font-size:1.1rem;" onclick={() => i > 0 && moveSlide(i, -1)}>arrow_upward</span>
              <!-- svelte-ignore a11y_click_events_have_key_events -->
              <!-- svelte-ignore a11y_no_static_element_interactions -->
              <span class="material-icons-round" title="Neeche le jaayein" style="cursor:{i === slides.length - 1 ? 'not-allowed' : 'pointer'}; opacity:{i === slides.length - 1 ? 0.3 : 1}; font-size:1.1rem;" onclick={() => i < slides.length - 1 && moveSlide(i, 1)}>arrow_downward</span>
              <!-- svelte-ignore a11y_click_events_have_key_events -->
              <!-- svelte-ignore a11y_no_static_element_interactions -->
              <span class="material-icons-round" title="Delete" style="cursor:pointer; color:var(--danger); font-size:1.1rem;" onclick={() => removeSlide(i)}>delete</span>
            {/if}
          </div>
        </div>

        <div class="form-group">
          <label style="font-size:0.8rem;">Image (optional)</label>
          <input type="file" accept="image/jpeg,image/png,image/gif,image/webp,image/heic,image/heif" onchange={(e) => { const f = (e.currentTarget as HTMLInputElement).files?.[0]; if (f) uploadSlideImage(i, f); }} />
          {#if uploadingSlide === i}<div class="inline-spinner">Uploading...</div>{/if}

          {#if slide.imageError}
            <div style="margin-top:8px; padding:8px 10px; border-radius:8px; background:#fdecea; color:var(--danger); font-size:0.8rem;">
              {slide.imageError}
            </div>
          {/if}

          {#if slide.imageUrl && !slide.imageBroken}
            <img
              src={driveImageUrl(slide.imageUrl)}
              alt=""
              style="max-width:100%; max-height:150px; margin-top:8px; border-radius:8px;"
              onerror={(e) => {
                const img = e.currentTarget as HTMLImageElement;
                if (img.dataset.driveFallbackTried !== '1') {
                  driveImgOnError(slide.imageUrl)(e);
                  if (img.dataset.driveFallbackTried === '1') return;
                }
                updateSlide(i, { imageBroken: true });
              }}
              onload={() => slide.imageBroken && updateSlide(i, { imageBroken: false })}
            />
          {/if}

          {#if slide.imageUrl && slide.imageBroken}
            <div style="margin-top:8px; padding:10px; border-radius:8px; border:1px dashed var(--danger); font-size:0.8rem;">
              <div style="font-weight:600; color:var(--danger); margin-bottom:4px;">
                The image failed to load — it will not show on the public portal either
              </div>
              <div style="color:var(--text-muted); word-break:break-all; margin-bottom:6px;">{slide.imageUrl}</div>
              <div style="display:flex; gap:8px; flex-wrap:wrap;">
                <a href={slide.imageUrl} target="_blank" rel="noreferrer">Open link</a>
                <button type="button" style={linkBtnStyle} onclick={() => updateSlide(i, { imageBroken: false })}>Try again</button>
                <button type="button" style={linkBtnStyle} onclick={() => updateSlide(i, { imageUrl: '', imageBroken: false, imageError: '' })}>Remove image</button>
              </div>
            </div>
          {/if}
        </div>

        <div class="form-group">
          <label style="font-size:0.8rem;">Text (optional)</label>
          <textarea rows={3} value={slide.text} oninput={(e) => updateSlide(i, { text: (e.currentTarget as HTMLTextAreaElement).value })} style="width:100%; padding:8px; border-radius:8px; border:1px solid #ddd;"></textarea>
        </div>

        <div class="form-group">
          <label style="font-size:0.8rem;">Link URL (optional)</label>
          <input value={slide.linkUrl} oninput={(e) => updateSlide(i, { linkUrl: (e.currentTarget as HTMLInputElement).value })} placeholder="https://..." />
        </div>
        {#if slide.linkUrl}
          <div class="form-group">
            <label style="font-size:0.8rem;">Link Text</label>
            <input value={slide.linkText} oninput={(e) => updateSlide(i, { linkText: (e.currentTarget as HTMLInputElement).value })} placeholder="e.g. More Info" />
          </div>
        {/if}

        <div class="form-group">
          <label style="font-size:0.8rem;">Auto-play duration (seconds)</label>
          <input
            type="number"
            min={MIN_DURATION_MS / 1000}
            max={MAX_DURATION_MS / 1000}
            step={1}
            value={Math.round((slide.durationMs ?? DEFAULT_DURATION_MS) / 1000)}
            oninput={(e) => {
              const secs = parseInt((e.currentTarget as HTMLInputElement).value, 10);
              updateSlide(i, { durationMs: Number.isFinite(secs) ? secs * 1000 : '' });
            }}
            onblur={() => updateSlide(i, { durationMs: clampDurationMs(slide.durationMs) })}
            style="max-width:120px;"
          />
          <div style="font-size:0.72rem; color:var(--text-muted); margin-top:4px;">
            {slides.length > 1
              ? `Is slide ke baad agli slide par jaane se pehle itni der rukega (${MIN_DURATION_MS / 1000}-${MAX_DURATION_MS / 1000}s). Aakhri slide ke baad wapas pehli par loop hota hai.`
              : `Auto-play sirf tab chalta hai jab 2 ya zyada slides hon — abhi ek hi slide hai.`}
          </div>
        </div>
      </div>
    {/each}
    <button type="button" class="btn-submit" style="width:auto; margin-top:10px; background:#e5e7eb; color:#111;" onclick={addSlide}>
      + Add Slide
    </button>
  </div>

  <div style="display:flex; gap:8px; flex-wrap:wrap;">
    <button class="btn-submit" style="width:auto;" onclick={save} disabled={saving}>{saving ? 'Saving...' : 'Save'}</button>
    <button type="button" class="btn-submit" style="width:auto; background:#111827; color:#fff;" onclick={() => (showLivePreview = true)}>👁 Live Preview</button>
    <button type="button" class="btn-submit" style="width:auto; background:#e5e7eb; color:#111;" onclick={cancelEdit}>Cancel</button>
  </div>

  {#if showLivePreview}
    <Modal open onClose={() => (showLivePreview = false)}>
      <h3 style="margin-top:0; margin-bottom:6px;">Live Preview</h3>
      <p style="font-size:0.75rem; color:var(--text-muted); margin-top:0; margin-bottom:14px;">
        Bilkul waisa hi jaisa public portal par dikhega — auto-play + loop chal raha hai; mouse le jaane par ruk jaata hai.
      </p>
      <PopupSlideshow slides={livePreviewSlides} />
    </Modal>
  {/if}
{:else}
  <div style="display:flex; justify-content:space-between; align-items:center; gap:8px; flex-wrap:wrap; margin-bottom:10px;">
    <h2 style="margin:0;">Popup Management</h2>
    <button type="button" class="btn-submit" style="width:auto; padding:6px 12px; font-size:0.8rem; background:#e5e7eb; color:#111;" onclick={runPreview} disabled={previewLoading}>
      {previewLoading ? 'Checking...' : '👁 Preview as Public'}
    </button>
  </div>
  <p style="font-size:0.75rem; color:var(--text-muted); margin-bottom:12px;">
    Popups are independent of the year — the year selector above does not apply to them.
  </p>
  {#if error}<div class="error-banner">{error}</div>{/if}

  {#if preview}
    <div class="glass-card" style="padding:15px; margin-bottom:15px;">
      <strong style="font-size:0.9rem;">What will show on the public portal right now</strong>
      {#if preview.shown.length === 0}
        <p style="font-size:0.8rem; color:var(--text-muted); margin:8px 0 0;">
          Nothing. To appear on the public portal, a popup must have the <strong>Public</strong> role,
          be Active, fall within its date window, and have at least 1 slide.
        </p>
      {:else}
        <p style="font-size:0.8rem; margin:8px 0 0;">
          ✅ <strong>{preview.shown[0].title}</strong> ({preview.shown[0].slides.length} slide{preview.shown[0].slides.length === 1 ? '' : 's'})
        </p>
      {/if}
      {#if preview.alsoEligibleButNotShown.length > 0}
        <div style="background:#FEF3C7; color:#92400E; border-radius:6px; padding:6px 10px; font-size:0.75rem; margin-top:8px;">
          ⚠️ The public portal shows only the <strong>first</strong> popup at a time. These are eligible but
          will not show: {preview.alsoEligibleButNotShown.map((x: any) => x.title).join(', ')}. Set their start/end
          times to different windows.
        </div>
      {/if}
      {#if preview.droppedNoSlides.length > 0}
        <div style="background:#FEE2E2; color:#991B1B; border-radius:6px; padding:6px 10px; font-size:0.75rem; margin-top:8px;">
          ⚠️ Dropped because they have no slides: {preview.droppedNoSlides.map((x: any) => x.title).join(', ')}
        </div>
      {/if}
      <button type="button" class="btn-submit" style="width:auto; margin-top:10px; padding:4px 10px; font-size:0.75rem; background:#e5e7eb; color:#111;" onclick={() => (preview = null)}>Close</button>
    </div>
  {/if}

  {#if !popups}<div class="inline-spinner">Loading...</div>{/if}
  {#if popups && popups.length === 0}<div class="glass-card" style="text-align:center; padding:20px;">No popups have been created yet.</div>{/if}

  {#each popups || [] as p (p.popup_id)}
    {@const isActive = isTruthyFlag(p.active)}
    {@const noSlides = p.slide_count === 0}
    {@const start = fmtStamp(p.start_at)}
    {@const end = fmtStamp(p.end_at)}
    {@const now = Date.now()}
    {@const notYet = p.start_at && new Date(p.start_at).getTime() > now}
    {@const over = p.end_at && new Date(p.end_at).getTime() < now}
    {@const liveNow = isActive && !noSlides && !notYet && !over}
    <div class="glass-card" style="padding:15px; margin-bottom:10px;">
      <div style="display:flex; justify-content:space-between; align-items:flex-start; gap:8px; flex-wrap:wrap;">
        <div>
          <strong>{p.title}</strong>
          <div style="font-size:0.8rem; color:var(--text-muted);">{p.roles || 'All roles'}</div>
          <div style="font-size:0.75rem; color:var(--text-muted);">{start || 'No start'} — {end || 'No end'}</div>
          <div style="font-size:0.75rem; color:var(--text-muted);">{p.slide_count} slide{p.slide_count === 1 ? '' : 's'}</div>
        </div>
        <div style="display:flex; flex-direction:column; gap:4px; align-items:flex-end;">
          <span class="badge {isActive ? 'badge-ok' : 'badge-warn'}">{isActive ? 'Active' : 'Inactive'}</span>
          {#if liveNow}<span class="badge badge-ok" style="font-size:0.65rem;">Showing now</span>{/if}
        </div>
      </div>

      {#if isActive && noSlides}
        <div style="background:#FEE2E2; color:#991B1B; border-radius:6px; padding:6px 10px; font-size:0.75rem; margin-top:8px;">
          ⚠️ This popup has no slides — it will <strong>not</strong> be shown to anyone. Edit it to add a slide.
        </div>
      {/if}
      {#if isActive && notYet}
        <div style="background:#FEF3C7; color:#92400E; border-radius:6px; padding:6px 10px; font-size:0.75rem; margin-top:8px;">
          ⏳ The start time has not arrived yet ({start}) — it will not show until then.
        </div>
      {/if}
      {#if isActive && over}
        <div style="background:#FEF3C7; color:#92400E; border-radius:6px; padding:6px 10px; font-size:0.75rem; margin-top:8px;">
          ⌛ The end time has passed ({end}) — it will no longer show.
        </div>
      {/if}
      <div class="row-actions" style="margin-top:10px;">
        <button type="button" class="icon-btn" title="Edit" onclick={() => startEdit(p.popup_id)}>
          <span class="material-icons-round" style="font-size:16px;">edit</span>
        </button>
        <button type="button" class="icon-btn icon-danger" title="Delete" onclick={() => remove(p.popup_id)}>
          <span class="material-icons-round" style="font-size:16px;">delete</span>
        </button>
      </div>
    </div>
  {/each}

  <button class="fab" onclick={startNew}><span class="material-icons-round">add</span></button>
{/if}
