// mgmt/frontend-svelte/src/lib/components/CleanupPanel.svelte
<script lang="ts">
  // Ported from React CleanupPanel.jsx — Superadmin-only panel to preview/delete
  // old or all records from a target table (used by Email + WhatsApp logs).
  import { api } from '$lib/api';
  import { isSuperadmin } from '$lib/permissions';

  interface Props {
    target: string;
    label: string;
    role: string;
    hasStatus?: boolean;
    onDone?: (() => void) | null;
  }
  let { target, label, role, hasStatus = false, onDone = null }: Props = $props();

  let mode = $state('olderThan');
  let days = $state('30');
  let count = $state<number | null>(null);
  let busy = $state(false);
  let error = $state('');

  async function preview() {
    error = '';
    count = null;
    busy = true;
    try {
      const r: any = await api.cleanupPreview(target, mode, mode === 'olderThan' ? days : undefined);
      count = r.count;
    } catch (e) {
      error = (e as Error).message;
    } finally {
      busy = false;
    }
  }

  async function run() {
    const desc = mode === 'all' ? 'ALL records' : mode === 'olderThan' ? `records older than ${days} day(s)` : `${mode} records`;
    if (!confirm(`Delete ${desc} from ${label}? This cannot be undone.`)) return;
    error = '';
    busy = true;
    try {
      const r: any = await api.cleanupData(target, mode, mode === 'olderThan' ? days : undefined);
      count = null;
      alert(`Removed ${r.removed} record(s) from ${label}.`);
      onDone && onDone();
    } catch (e) {
      error = (e as Error).message;
    } finally {
      busy = false;
    }
  }
</script>

{#if isSuperadmin(role)}
  <div class="glass-card" style="padding:14px; margin-top:12px; border:1px solid #fde68a; background:#fffbeb;">
    <strong style="display:block; margin-bottom:8px;">🧹 Clean up {label}</strong>
    {#if error}<div class="error-banner" style="margin-bottom:8px;">{error}</div>{/if}
    <div class="form-group" style="margin-bottom:8px;">
      <label style="font-size:0.8rem;">What to delete</label>
      <select value={mode} onchange={(e) => { mode = (e.currentTarget as HTMLSelectElement).value; count = null; }}>
        <option value="olderThan">Keep last N days (delete older)</option>
        {#if hasStatus}<option value="sent">Only Sent</option>{/if}
        {#if hasStatus}<option value="failed">Only Failed</option>{/if}
        <option value="all">Everything (All)</option>
      </select>
    </div>
    {#if mode === 'olderThan'}
      <div class="form-group" style="margin-bottom:8px;">
        <label style="font-size:0.8rem;">Keep last (days)</label>
        <input type="number" min="0" value={days} oninput={(e) => { days = (e.currentTarget as HTMLInputElement).value; count = null; }} style="width:120px;" />
      </div>
    {/if}
    <div style="display:flex; gap:8px; align-items:center; flex-wrap:wrap;">
      <button type="button" class="btn-submit" style="width:auto; background:#e5e7eb; color:#111;" onclick={preview} disabled={busy}>
        {busy ? '...' : 'Preview count'}
      </button>
      <button type="button" class="btn-submit" style="width:auto; background:var(--danger, #dc2626);" onclick={run} disabled={busy}>
        {busy ? 'Working...' : 'Delete'}
      </button>
      {#if count !== null}<span style="font-size:0.85rem; color:var(--text-muted);">{count} record(s) match</span>{/if}
    </div>
  </div>
{/if}

// mgmt/frontend/src/components/CleanupPanel.jsx
import { useState } from 'react';
import { api } from '../api.js';
import { isSuperadmin } from '../permissions.js';

export default function CleanupPanel({ target, label, role, hasStatus = false, onDone }) {
  const [mode, setMode] = useState('olderThan');
  const [days, setDays] = useState('30');
  const [count, setCount] = useState(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');

  if (!isSuperadmin(role)) return null;

  const preview = async () => {
    setError(''); setCount(null); setBusy(true);
    try {
      const r = await api.cleanupPreview(target, mode, mode === 'olderThan' ? days : undefined);
      setCount(r.count);
    } catch (e) { setError(e.message); } finally { setBusy(false); }
  };

  const run = async () => {
    const desc = mode === 'all' ? 'ALL records' : mode === 'olderThan' ? `records older than ${days} day(s)` : `${mode} records`;
    if (!confirm(`Delete ${desc} from ${label}? This cannot be undone.`)) return;
    setError(''); setBusy(true);
    try {
      const r = await api.cleanupData(target, mode, mode === 'olderThan' ? days : undefined);
      setCount(null);
      alert(`Removed ${r.removed} record(s) from ${label}.`);
      onDone && onDone();
    } catch (e) { setError(e.message); } finally { setBusy(false); }
  };

  return (
    <div className="glass-card" style={{ padding: 14, marginTop: 12, border: '1px solid #fde68a', background: '#fffbeb' }}>
      <strong style={{ display: 'block', marginBottom: 8 }}>🧹 Clean up {label}</strong>
      {error && <div className="error-banner" style={{ marginBottom: 8 }}>{error}</div>}
      <div className="form-group" style={{ marginBottom: 8 }}>
        <label style={{ fontSize: '0.8rem' }}>What to delete</label>
        <select value={mode} onChange={e => { setMode(e.target.value); setCount(null); }}>
          <option value="olderThan">Keep last N days (delete older)</option>
          {hasStatus && <option value="sent">Only Sent</option>}
          {hasStatus && <option value="failed">Only Failed</option>}
          <option value="all">Everything (All)</option>
        </select>
      </div>
      {mode === 'olderThan' && (
        <div className="form-group" style={{ marginBottom: 8 }}>
          <label style={{ fontSize: '0.8rem' }}>Keep last (days)</label>
          <input type="number" min="0" value={days} onChange={e => { setDays(e.target.value); setCount(null); }} style={{ width: 120 }} />
        </div>
      )}
      <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}>
        <button type="button" className="btn-submit" style={{ width: 'auto', background: '#e5e7eb', color: '#111' }} onClick={preview} disabled={busy}>
          {busy ? '...' : 'Preview count'}
        </button>
        <button type="button" className="btn-submit" style={{ width: 'auto', background: 'var(--danger, #dc2626)' }} onClick={run} disabled={busy}>
          {busy ? 'Working...' : 'Delete'}
        </button>
        {count !== null && <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>{count} record(s) match</span>}
      </div>
    </div>
  );
}
