// mgmt/frontend-svelte/src/lib/components/ForgotPassword.svelte
<script lang="ts">
  // Ported from React ForgotPassword.jsx — request code -> reset flow, same
  // error codes (NOT_FOUND / NO_EMAIL / RATE_LIMITED) and copy.
  import { api } from '$lib/api';

  interface Props {
    initialName?: string;
    onCancel: () => void;
    onDone: (msg: string) => void;
  }
  let { initialName = '', onCancel, onDone }: Props = $props();

  let step = $state<'request' | 'reset'>('request');
  let name = $state(initialName);
  let code = $state('');
  let newPassword = $state('');
  let confirm = $state('');
  let error = $state('');
  let info = $state('');
  let loading = $state(false);

  async function requestCode(e: Event) {
    e.preventDefault();
    error = '';
    if (!name.trim()) { error = 'Enter your username, mobile, or email.'; return; }
    loading = true;
    try {
      const res: any = await api.requestPasswordReset(name.trim());
      info = (res && res.message) || 'A 6-digit reset code has been sent.';
      step = 'reset';
    } catch (e2) {
      const err = e2 as any;
      if (err && err.code === 'NOT_FOUND') {
        error = 'No account found with that username, mobile, or email.';
      } else if (err && err.code === 'NO_EMAIL') {
        error = 'This account has no email on file. Contact a committee admin to reset your password.';
      } else if (err && err.code === 'RATE_LIMITED') {
        const secs = Number(err.retryAfterSeconds) || 0;
        const mins = Math.max(1, Math.ceil(secs / 60));
        error = err.message || `Too many reset requests. Try again in ${mins} minute${mins === 1 ? '' : 's'}.`;
      } else {
        error = (err && err.message) || 'Could not start password reset.';
      }
    } finally {
      loading = false;
    }
  }

  async function doReset(e: Event) {
    e.preventDefault();
    error = '';
    if (!code.trim()) { error = 'Enter the 6-digit code from your email.'; return; }
    if (!newPassword) { error = 'Enter a new password.'; return; }
    if (newPassword !== confirm) { error = 'The two passwords do not match.'; return; }
    loading = true;
    try {
      const res: any = await api.resetPassword(name.trim(), code.trim(), newPassword);
      onDone((res && res.message) || 'Your password has been reset. Please sign in.');
    } catch (e2) {
      error = (e2 as Error).message || 'Could not reset the password.';
    } finally {
      loading = false;
    }
  }
</script>

<div class="glass-card">
  <h3 style="margin-top:0;">Reset your password</h3>
  {#if error}<div class="error-banner">{error}</div>{/if}
  {#if info && step === 'reset'}
    <div style="background:rgba(22,163,74,0.08); border:1px solid #16a34a33; border-radius:8px; padding:8px 10px; font-size:0.82rem; margin-bottom:12px;">
      {info}
    </div>
  {/if}

  {#if step === 'request'}
    <form onsubmit={requestCode}>
      <div class="form-group">
        <label>Username / Mobile / Email</label>
        <!-- svelte-ignore a11y_autofocus -->
        <input bind:value={name} autocomplete="username" placeholder="Username, Mobile, or Email" autofocus />
      </div>
      <p style="font-size:0.78rem; color:var(--text-muted); margin:0 0 12px;">
        We'll email a 6-digit reset code to the address on your account. If you have no email on file, contact a committee admin.
      </p>
      <button class="btn-submit" type="submit" disabled={loading}>{loading ? 'Sending…' : 'Send reset code'}</button>
    </form>
  {:else}
    <form onsubmit={doReset}>
      <div class="form-group">
        <label>6-digit code</label>
        <!-- svelte-ignore a11y_autofocus -->
        <input
          value={code}
          oninput={(e) => (code = (e.currentTarget as HTMLInputElement).value.replace(/\D/g, '').slice(0, 6))}
          inputmode="numeric"
          autocomplete="one-time-code"
          placeholder="000000"
          maxlength="6"
          autofocus
          style="letter-spacing:0.3em; text-align:center; font-size:1.2rem;"
        />
      </div>
      <div class="form-group">
        <label>New password</label>
        <input type="password" bind:value={newPassword} autocomplete="new-password" />
      </div>
      <div class="form-group">
        <label>Confirm new password</label>
        <input type="password" bind:value={confirm} autocomplete="new-password" />
      </div>
      <p style="font-size:0.75rem; color:var(--text-muted); margin:0 0 12px;">
        Use at least 8 characters. Superadmin accounts need 12+ with an uppercase letter, a lowercase letter and a number.
      </p>
      <button class="btn-submit" type="submit" disabled={loading}>{loading ? 'Resetting…' : 'Reset password'}</button>
      <button
        type="button"
        onclick={() => { step = 'request'; error = ''; }}
        disabled={loading}
        style="display:block; margin:10px auto 0; background:none; border:none; color:var(--text-muted); cursor:pointer; font-size:0.82rem;"
      >
        ← Didn't get a code? Try again
      </button>
    </form>
  {/if}

  <button
    type="button"
    onclick={onCancel}
    disabled={loading}
    style="display:block; margin:16px auto 0; background:none; border:none; color:var(--text-muted); cursor:pointer; font-size:0.82rem;"
  >
    ← Back to login
  </button>
</div>

// mgmt/frontend/src/components/ForgotPassword.jsx
import { useState } from 'react';
import { api } from '../api.js';

export default function ForgotPassword({ initialName = '', onCancel, onDone }) {
  const [step, setStep] = useState('request');
  const [name, setName] = useState(initialName);
  const [code, setCode] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const [confirm, setConfirm] = useState('');
  const [error, setError] = useState('');
  const [info, setInfo] = useState('');
  const [loading, setLoading] = useState(false);

  const requestCode = async (e) => {
    e.preventDefault();
    setError('');
    if (!name.trim()) return setError('Enter your username, mobile, or email.');
    setLoading(true);
    try {
      const res = await api.requestPasswordReset(name.trim());
      setInfo((res && res.message) || 'A 6-digit reset code has been sent.');
      setStep('reset');
    } catch (err) {
      if (err && err.code === 'NOT_FOUND') {
        setError('No account found with that username, mobile, or email.');
      } else if (err && err.code === 'NO_EMAIL') {
        setError('This account has no email on file. Contact a committee admin to reset your password.');
      } else if (err && err.code === 'RATE_LIMITED') {
        const secs = Number(err.retryAfterSeconds) || 0;
        const mins = Math.max(1, Math.ceil(secs / 60));
        setError(err.message || `Too many reset requests. Try again in ${mins} minute${mins === 1 ? '' : 's'}.`);
      } else {
        setError((err && err.message) || 'Could not start password reset.');
      }
    } finally {
      setLoading(false);
    }
  };

  const doReset = async (e) => {
    e.preventDefault();
    setError('');
    if (!code.trim()) return setError('Enter the 6-digit code from your email.');
    if (!newPassword) return setError('Enter a new password.');
    if (newPassword !== confirm) return setError('The two passwords do not match.');
    setLoading(true);
    try {
      const res = await api.resetPassword(name.trim(), code.trim(), newPassword);
      onDone((res && res.message) || 'Your password has been reset. Please sign in.');
    } catch (err) {
      setError(err.message || 'Could not reset the password.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="glass-card">
      <h3 style={{ marginTop: 0 }}>Reset your password</h3>
      {error && <div className="error-banner">{error}</div>}
      {info && step === 'reset' && (
        <div style={{ background: 'rgba(22,163,74,0.08)', border: '1px solid #16a34a33', borderRadius: 8, padding: '8px 10px', fontSize: '0.82rem', marginBottom: 12 }}>
          {info}
        </div>
      )}

      {step === 'request' ? (
        <form onSubmit={requestCode}>
          <div className="form-group">
            <label>Username / Mobile / Email</label>
            <input
              value={name}
              onChange={e => setName(e.target.value)}
              autoComplete="username"
              placeholder="Username, Mobile, or Email"
              autoFocus
            />
          </div>
          <p style={{ fontSize: '0.78rem', color: 'var(--text-muted)', margin: '0 0 12px' }}>
            We'll email a 6-digit reset code to the address on your account. If you
            have no email on file, contact a committee admin.
          </p>
          <button className="btn-submit" type="submit" disabled={loading}>
            {loading ? 'Sending…' : 'Send reset code'}
          </button>
        </form>
      ) : (
        <form onSubmit={doReset}>
          <div className="form-group">
            <label>6-digit code</label>
            <input
              value={code}
              onChange={e => setCode(e.target.value.replace(/\D/g, '').slice(0, 6))}
              inputMode="numeric"
              autoComplete="one-time-code"
              placeholder="000000"
              maxLength={6}
              autoFocus
              style={{ letterSpacing: '0.3em', textAlign: 'center', fontSize: '1.2rem' }}
            />
          </div>
          <div className="form-group">
            <label>New password</label>
            <input type="password" value={newPassword} onChange={e => setNewPassword(e.target.value)} autoComplete="new-password" />
          </div>
          <div className="form-group">
            <label>Confirm new password</label>
            <input type="password" value={confirm} onChange={e => setConfirm(e.target.value)} autoComplete="new-password" />
          </div>
          <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', margin: '0 0 12px' }}>
            Use at least 8 characters. Superadmin accounts need 12+ with an
            uppercase letter, a lowercase letter and a number.
          </p>
          <button className="btn-submit" type="submit" disabled={loading}>
            {loading ? 'Resetting…' : 'Reset password'}
          </button>
          <button
            type="button"
            onClick={() => { setStep('request'); setError(''); }}
            disabled={loading}
            style={{ display: 'block', margin: '10px auto 0', background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', fontSize: '0.82rem' }}
          >
            ← Didn't get a code? Try again
          </button>
        </form>
      )}

      <button
        type="button"
        onClick={onCancel}
        disabled={loading}
        style={{ display: 'block', margin: '16px auto 0', background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', fontSize: '0.82rem' }}
      >
        ← Back to login
      </button>
    </div>
  );
}
