// mgmt/frontend-svelte/src/lib/components/TransliterateInput.svelte
<script lang="ts">
  // Ported from React TransliterateInput.jsx — English input auto-transliterated
  // to Hindi (debounced 400ms) with a toggle to edit the Hindi manually.
  import { transliterate } from '$lib/transliterate';

  interface Val { en: string; hi: string; }
  interface Props {
    label: string;
    value: Val;
    onChange: (v: Val) => void;
    placeholder?: string;
    listId?: string;
  }
  let { label, value, onChange, placeholder = '', listId }: Props = $props();

  let en = $derived(value?.en || '');
  let hi = $derived(value?.hi || '');
  let manualHi = $state(false);
  let hiEditable = $state(false);
  let debounceId: ReturnType<typeof setTimeout> | null = null;

  // Auto-transliterate when the English text changes (unless Hindi was edited).
  $effect(() => {
    const cur = en;
    if (manualHi) return;
    if (!cur) {
      onChange({ en: cur, hi: '' });
      return;
    }
    if (debounceId) clearTimeout(debounceId);
    debounceId = setTimeout(async () => {
      const result = await transliterate(cur);
      onChange({ en: cur, hi: result });
    }, 400);
    return () => {
      if (debounceId) clearTimeout(debounceId);
    };
  });
</script>

<div class="form-group">
  <label>{label}</label>
  <input
    value={en}
    {placeholder}
    list={listId}
    oninput={(e) => {
      const v = (e.currentTarget as HTMLInputElement).value;
      if (!v) manualHi = false;
      onChange({ en: v, hi });
    }}
  />
  <div style="display:flex; align-items:center; gap:6px; margin-top:6px;">
    <input
      value={hi}
      placeholder={`${label} (Hindi)`}
      readonly={!hiEditable}
      style="background:{hiEditable ? '#fff' : '#f9fafb'}; flex-grow:1;"
      oninput={(e) => { manualHi = true; onChange({ en, hi: (e.currentTarget as HTMLInputElement).value }); }}
    />
    <!-- svelte-ignore a11y_click_events_have_key_events -->
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <span
      class="material-icons-round"
      style="cursor:pointer; font-size:1.1rem; color:{hiEditable ? 'var(--primary-saffron)' : 'var(--text-muted)'};"
      title="Edit Hindi text"
      onclick={() => (hiEditable = !hiEditable)}
    >
      edit
    </span>
  </div>
</div>

// mgmt/frontend/src/components/TransliterateInput.jsx
import { useState, useEffect, useRef } from 'react';
import { transliterate } from '../transliterate.js';

export default function TransliterateInput({ label, value, onChange, placeholder, listId }) {
  const en = value?.en || '';
  const hi = value?.hi || '';
  const [manualHi, setManualHi] = useState(false);
  const [hiEditable, setHiEditable] = useState(false);
  const debounceRef = useRef(null);

  useEffect(() => {
    if (manualHi) return;
    if (!en) { onChange({ en, hi: '' }); return; }
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(async () => {
      const result = await transliterate(en);
      onChange({ en, hi: result });
    }, 400);
    return () => { if (debounceRef.current) clearTimeout(debounceRef.current); };
  }, [en]);

  return (
    <div className="form-group">
      <label>{label}</label>
      <input
        value={en}
        placeholder={placeholder}
        list={listId}
        onChange={e => {
          const v = e.target.value;
          if (!v) setManualHi(false);
          onChange({ en: v, hi });
        }}
      />
      <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginTop: 6 }}>
        <input
          value={hi}
          placeholder={`${label} (Hindi)`}
          readOnly={!hiEditable}
          style={{ background: hiEditable ? '#fff' : '#f9fafb', flexGrow: 1 }}
          onChange={e => { setManualHi(true); onChange({ en, hi: e.target.value }); }}
        />
        <span
          className="material-icons-round"
          style={{ cursor: 'pointer', fontSize: '1.1rem', color: hiEditable ? 'var(--primary-saffron)' : 'var(--text-muted)' }}
          title="Edit Hindi text"
          onClick={() => setHiEditable(v => !v)}
        >
          edit
        </span>
      </div>
    </div>
  );
}
