// mgmt/frontend/src/components/LoanConsentModal.jsx
import { useEffect, useState } from 'react';
import { api } from '../api.js';
import { invalidate } from '../cache.js';
import Modal from './Modal.jsx';
import SearchableSelect from './SearchableSelect.jsx';
import { isSuperadmin, isAdminOrAbove } from '../permissions.js';

const STATUS_LABEL = { pending: 'Pending', accepted: 'Accepted', declined: 'Declined', replaced: 'Replaced' };
const STATUS_BADGE = { pending: 'badge-warn', accepted: 'badge-ok', declined: 'badge-danger', replaced: 'badge-warn' };

export default function LoanConsentModal({ loan, open, onClose, role, contributorOptions, onChanged }) {
  const [consents, setConsents] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [busyId, setBusyId] = useState(null);
  const [replacingId, setReplacingId] = useState(null);
  const [newGuarantor, setNewGuarantor] = useState('');
  const [showDisburseForm, setShowDisburseForm] = useState(false);
  const [cashAmount, setCashAmount] = useState('');
  const [onlineAmount, setOnlineAmount] = useState('');

  const loanId = loan && loan['Loan ID'];

  const load = () => {
    if (!loanId) return;
    setLoading(true);
    api.getLoanConsents(loanId).then(setConsents).catch(err => setError(err.message)).finally(() => setLoading(false));
  };

  useEffect(() => { if (open) load();  }, [open, loanId]);

  if (!loanId) {
    return (
      <Modal open={open} onClose={onClose}>
        <p style={{ padding: 20 }}>This is an older loan (predates the Consent system) — no consent record is available.</p>
      </Modal>
    );
  }

  const resend = async (consentId) => {
    setBusyId(consentId);
    setError('');
    try {
      await api.resendConsent(consentId);
      load();
    } catch (err) {
      setError(err.message);
    } finally {
      setBusyId(null);
    }
  };

  const startReplace = (consentId) => { setReplacingId(consentId); setNewGuarantor(''); };

  const confirmReplace = async (consentId) => {
    if (!newGuarantor) return alert('Please select a new guarantor');
    setBusyId(consentId);
    setError('');
    try {
      await api.replaceGuarantor(loanId, consentId, newGuarantor);
      setReplacingId(null);
      load();
    } catch (err) {
      setError(err.message);
    } finally {
      setBusyId(null);
    }
  };

  const disburse = async () => {
    const cash = parseFloat(cashAmount) || 0;
    const online = parseFloat(onlineAmount) || 0;
    const amt = parseFloat(loan && (loan.Amount ?? loan['Amount'])) || 0;
    if (cash <= 0 && online <= 0) return alert('Please enter at least one amount — Cash or Online.');
    if (Math.abs((cash + online) - amt) > 0.01) return alert(`Total (₹${cash + online}) must equal the loan amount ₹${amt}. Adjust the Cash / Online split.`);
    if (!confirm(`Disburse: Cash ₹${cash} + Online ₹${online} = Total ₹${cash + online}. Confirm?`)) return;
    setBusyId('disburse');
    setError('');
    try {
      await api.markLoanDisbursed(loanId, cash, online);
      invalidate('loans:');
      onChanged && onChanged();
      onClose();
    } catch (err) {
      setError(err.message);
    } finally {
      setBusyId(null);
    }
  };

  const allAccepted = (consents || []).filter(c => c.status !== 'replaced').every(c => c.status === 'accepted') && (consents || []).length > 0;
  const canDisburse = isAdminOrAbove(role) && loan['Loan Status'] === 'Approved';
  const loanAmount = parseFloat(loan && (loan.Amount ?? loan['Amount'])) || 0;
  const disburseTotal = (parseFloat(cashAmount) || 0) + (parseFloat(onlineAmount) || 0);
  const disburseMatches = Math.abs(disburseTotal - loanAmount) <= 0.01;

  return (
    <Modal open={open} onClose={onClose}>
      <h3 style={{ marginBottom: 5 }}>Loan Status</h3>
      <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: 15 }}>
        Loan ID: {loanId} — <strong>{loan['Loan Status'] || 'Created'}</strong>
      </p>

      {error && <div className="error-banner" style={{ marginBottom: 10 }}>{error}</div>}
      {loading && <div className="inline-spinner">Loading...</div>}

      {!loading && (consents || []).filter(c => c.status !== 'replaced').map(c => (
        <div className="glass-card" style={{ padding: 12, marginBottom: 10 }} key={c.consent_id}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <div>
              <strong>{c.personName}</strong>{c.personNameHindi ? ` (${c.personNameHindi})` : ''}
              <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>{c.role === 'loaner' ? 'Loan Receiver' : 'Guarantor'} — Sent {c.send_count}/5</div>
            </div>
            <span className={`badge ${STATUS_BADGE[c.status] || 'badge-warn'}`}>{STATUS_LABEL[c.status] || c.status}</span>
          </div>

          {isSuperadmin(role) && c.status !== 'accepted' && (
            <div style={{ display: 'flex', gap: 8, marginTop: 10, flexWrap: 'wrap' }}>
              <button
                type="button"
                className="btn-submit"
                style={{ width: 'auto', padding: '6px 12px', fontSize: '0.8rem' }}
                onClick={() => resend(c.consent_id)}
                disabled={busyId === c.consent_id || parseInt(c.send_count) >= 5}
              >
                {parseInt(c.send_count) >= 5 ? 'Max reached' : 'Resend'}
              </button>
              {c.role === 'guarantor' && (
                <button
                  type="button"
                  className="btn-submit"
                  style={{ width: 'auto', padding: '6px 12px', fontSize: '0.8rem', background: '#e5e7eb', color: '#111' }}
                  onClick={() => startReplace(c.consent_id)}
                >
                  Change Guarantor
                </button>
              )}
            </div>
          )}

          {replacingId === c.consent_id && (
            <div style={{ marginTop: 10, background: '#f9fafb', padding: 10, borderRadius: 8 }}>
              <label style={{ fontSize: '0.8rem', display: 'block', marginBottom: 6 }}>New Guarantor</label>
              <SearchableSelect options={contributorOptions || []} value={newGuarantor} onChange={setNewGuarantor} />
              <div style={{ display: 'flex', gap: 8, marginTop: 8 }}>
                <button type="button" className="btn-submit" style={{ width: 'auto', padding: '6px 12px', fontSize: '0.8rem' }} onClick={() => confirmReplace(c.consent_id)} disabled={busyId === c.consent_id}>Confirm</button>
                <button type="button" className="btn-submit" style={{ width: 'auto', padding: '6px 12px', fontSize: '0.8rem', background: '#e5e7eb', color: '#111' }} onClick={() => setReplacingId(null)}>Cancel</button>
              </div>
            </div>
          )}
        </div>
      ))}

      {canDisburse && !showDisburseForm && (
        <button className="btn-submit" style={{ marginTop: 10 }} onClick={() => setShowDisburseForm(true)}>
          Mark as Disbursed
        </button>
      )}

      {canDisburse && showDisburseForm && (
        <div className="glass-card" style={{ padding: 12, marginTop: 10 }}>
          <p style={{ fontSize: '0.85rem', marginTop: 0, marginBottom: 8 }}>
            Sanctioned loan amount: <strong>₹{loanAmount}</strong> — Cash + Online must add up to exactly this.
          </p>
          <label style={{ fontSize: '0.8rem' }}>Cash Amount (₹)</label>
          <input type="number" min="0" className="input-field" value={cashAmount} onChange={e => setCashAmount(e.target.value)} placeholder="0" />
          <label style={{ fontSize: '0.8rem', marginTop: 8, display: 'block' }}>Online Amount (₹)</label>
          <input type="number" min="0" className="input-field" value={onlineAmount} onChange={e => setOnlineAmount(e.target.value)} placeholder="0" />
          <p style={{ fontSize: '0.8rem', marginTop: 6, color: disburseMatches ? 'var(--text-main)' : 'var(--danger)' }}>
            Total: ₹{disburseTotal}{disburseMatches ? ' ✓' : ` — must equal ₹${loanAmount}`}
          </p>
          <div style={{ display: 'flex', gap: 8, marginTop: 10 }}>
            <button className="btn-submit" style={{ width: 'auto' }} onClick={disburse} disabled={busyId === 'disburse' || !disburseMatches}>
              {busyId === 'disburse' ? 'Marking...' : 'Confirm Disburse'}
            </button>
            <button type="button" className="btn-submit" style={{ width: 'auto', background: '#e5e7eb', color: '#111' }} onClick={() => setShowDisburseForm(false)}>Cancel</button>
          </div>
        </div>
      )}
    </Modal>
  );
}

// mgmt/frontend-svelte/src/lib/components/LoanConsentModal.svelte
<script lang="ts">
  // Ported from React LoanConsentModal.jsx — shows per-loan consent records,
  // resend/replace-guarantor (superadmin), and cash/online disbursement (admin+).
  import { api } from '$lib/api';
  import { invalidate } from '$lib/cache';
  import Modal from './Modal.svelte';
  import SearchableSelect from './SearchableSelect.svelte';
  import { isSuperadmin, isAdminOrAbove } from '$lib/permissions';

  interface Props {
    loan: any;
    open: boolean;
    onClose: () => void;
    role: string;
    contributorOptions: any[];
    onChanged?: (() => void) | null;
  }
  let { loan, open, onClose, role, contributorOptions, onChanged = null }: Props = $props();

  const STATUS_LABEL: Record<string, string> = { pending: 'Pending', accepted: 'Accepted', declined: 'Declined', replaced: 'Replaced' };
  const STATUS_BADGE: Record<string, string> = { pending: 'badge-warn', accepted: 'badge-ok', declined: 'badge-danger', replaced: 'badge-warn' };

  let consents = $state<any[] | null>(null);
  let loading = $state(true);
  let error = $state('');
  let busyId = $state<string | null>(null);
  let replacingId = $state<string | null>(null);
  let newGuarantor = $state('');
  let showDisburseForm = $state(false);
  let cashAmount = $state('');
  let onlineAmount = $state('');

  let loanId = $derived(loan && loan['Loan ID']);

  function load() {
    if (!loanId) return;
    loading = true;
    api.getLoanConsents(loanId)
      .then((c: any) => (consents = c))
      .catch((err: Error) => (error = err.message))
      .finally(() => (loading = false));
  }

  // React: useEffect on [open, loanId] -> load when open
  let lastKey = '';
  $effect(() => {
    const key = `${open}|${loanId}`;
    if (key === lastKey) return;
    lastKey = key;
    if (open) load();
  });

  async function resend(consentId: string) {
    busyId = consentId;
    error = '';
    try {
      await api.resendConsent(consentId);
      load();
    } catch (err) {
      error = (err as Error).message;
    } finally {
      busyId = null;
    }
  }

  function startReplace(consentId: string) { replacingId = consentId; newGuarantor = ''; }

  async function confirmReplace(consentId: string) {
    if (!newGuarantor) { alert('Please select a new guarantor'); return; }
    busyId = consentId;
    error = '';
    try {
      await api.replaceGuarantor(loanId, consentId, newGuarantor);
      replacingId = null;
      load();
    } catch (err) {
      error = (err as Error).message;
    } finally {
      busyId = null;
    }
  }

  async function disburse() {
    const cash = parseFloat(cashAmount) || 0;
    const online = parseFloat(onlineAmount) || 0;
    const amt = parseFloat(loan && (loan.Amount ?? loan['Amount'])) || 0;
    if (cash <= 0 && online <= 0) { alert('Please enter at least one amount — Cash or Online.'); return; }
    if (Math.abs((cash + online) - amt) > 0.01) { alert(`Total (₹${cash + online}) must equal the loan amount ₹${amt}. Adjust the Cash / Online split.`); return; }
    if (!confirm(`Disburse: Cash ₹${cash} + Online ₹${online} = Total ₹${cash + online}. Confirm?`)) return;
    busyId = 'disburse';
    error = '';
    try {
      await api.markLoanDisbursed(loanId, cash, online);
      invalidate('loans:');
      onChanged && onChanged();
      onClose();
    } catch (err) {
      error = (err as Error).message;
    } finally {
      busyId = null;
    }
  }

  let visibleConsents = $derived((consents || []).filter((c) => c.status !== 'replaced'));
  let canDisburse = $derived(isAdminOrAbove(role) && loan && loan['Loan Status'] === 'Approved');
  let loanAmount = $derived(parseFloat(loan && (loan.Amount ?? loan['Amount'])) || 0);
  let disburseTotal = $derived((parseFloat(cashAmount) || 0) + (parseFloat(onlineAmount) || 0));
  let disburseMatches = $derived(Math.abs(disburseTotal - loanAmount) <= 0.01);
</script>

{#if !loanId}
  <Modal {open} {onClose}>
    <p style="padding:20px;">This is an older loan (predates the Consent system) — no consent record is available.</p>
  </Modal>
{:else}
  <Modal {open} {onClose}>
    <h3 style="margin-bottom:5px;">Loan Status</h3>
    <p style="font-size:0.85rem; color:var(--text-muted); margin-bottom:15px;">
      Loan ID: {loanId} — <strong>{loan['Loan Status'] || 'Created'}</strong>
    </p>

    {#if error}<div class="error-banner" style="margin-bottom:10px;">{error}</div>{/if}
    {#if loading}<div class="inline-spinner">Loading...</div>{/if}

    {#if !loading}
      {#each visibleConsents as c (c.consent_id)}
        <div class="glass-card" style="padding:12px; margin-bottom:10px;">
          <div style="display:flex; justify-content:space-between; align-items:center;">
            <div>
              <strong>{c.personName}</strong>{c.personNameHindi ? ` (${c.personNameHindi})` : ''}
              <div style="font-size:0.75rem; color:var(--text-muted);">{c.role === 'loaner' ? 'Loan Receiver' : 'Guarantor'} — Sent {c.send_count}/5</div>
            </div>
            <span class="badge {STATUS_BADGE[c.status] || 'badge-warn'}">{STATUS_LABEL[c.status] || c.status}</span>
          </div>

          {#if isSuperadmin(role) && c.status !== 'accepted'}
            <div style="display:flex; gap:8px; margin-top:10px; flex-wrap:wrap;">
              <button
                type="button"
                class="btn-submit"
                style="width:auto; padding:6px 12px; font-size:0.8rem;"
                onclick={() => resend(c.consent_id)}
                disabled={busyId === c.consent_id || parseInt(c.send_count) >= 5}
              >
                {parseInt(c.send_count) >= 5 ? 'Max reached' : 'Resend'}
              </button>
              {#if c.role === 'guarantor'}
                <button
                  type="button"
                  class="btn-submit"
                  style="width:auto; padding:6px 12px; font-size:0.8rem; background:#e5e7eb; color:#111;"
                  onclick={() => startReplace(c.consent_id)}
                >
                  Change Guarantor
                </button>
              {/if}
            </div>
          {/if}

          {#if replacingId === c.consent_id}
            <div style="margin-top:10px; background:#f9fafb; padding:10px; border-radius:8px;">
              <label style="font-size:0.8rem; display:block; margin-bottom:6px;">New Guarantor</label>
              <SearchableSelect options={contributorOptions || []} value={newGuarantor} onChange={(v) => (newGuarantor = v)} />
              <div style="display:flex; gap:8px; margin-top:8px;">
                <button type="button" class="btn-submit" style="width:auto; padding:6px 12px; font-size:0.8rem;" onclick={() => confirmReplace(c.consent_id)} disabled={busyId === c.consent_id}>Confirm</button>
                <button type="button" class="btn-submit" style="width:auto; padding:6px 12px; font-size:0.8rem; background:#e5e7eb; color:#111;" onclick={() => (replacingId = null)}>Cancel</button>
              </div>
            </div>
          {/if}
        </div>
      {/each}
    {/if}

    {#if canDisburse && !showDisburseForm}
      <button class="btn-submit" style="margin-top:10px;" onclick={() => (showDisburseForm = true)}>
        Mark as Disbursed
      </button>
    {/if}

    {#if canDisburse && showDisburseForm}
      <div class="glass-card" style="padding:12px; margin-top:10px;">
        <p style="font-size:0.85rem; margin-top:0; margin-bottom:8px;">
          Sanctioned loan amount: <strong>₹{loanAmount}</strong> — Cash + Online must add up to exactly this.
        </p>
        <label style="font-size:0.8rem;">Cash Amount (₹)</label>
        <input type="number" min="0" class="input-field" bind:value={cashAmount} placeholder="0" />
        <label style="font-size:0.8rem; margin-top:8px; display:block;">Online Amount (₹)</label>
        <input type="number" min="0" class="input-field" bind:value={onlineAmount} placeholder="0" />
        <p style="font-size:0.8rem; margin-top:6px; color:{disburseMatches ? 'var(--text-main)' : 'var(--danger)'};">
          Total: ₹{disburseTotal}{disburseMatches ? ' ✓' : ` — must equal ₹${loanAmount}`}
        </p>
        <div style="display:flex; gap:8px; margin-top:10px;">
          <button class="btn-submit" style="width:auto;" onclick={disburse} disabled={busyId === 'disburse' || !disburseMatches}>
            {busyId === 'disburse' ? 'Marking...' : 'Confirm Disburse'}
          </button>
          <button type="button" class="btn-submit" style="width:auto; background:#e5e7eb; color:#111;" onclick={() => (showDisburseForm = false)}>Cancel</button>
        </div>
      </div>
    {/if}
  </Modal>
{/if}
