// mgmt/frontend/src/components/LoginPopups.jsx
import { useEffect, useRef, useState } from 'react';
import { api } from '../api.js';
import Modal from './Modal.jsx';
import { driveImageUrl, driveImgOnError } from '../driveUrl.js';

const DEFAULT_DURATION_MS = 5000;
function clampDurationMs(ms) {
  const n = parseInt(ms, 10);
  if (!Number.isFinite(n) || n <= 0) return DEFAULT_DURATION_MS;
  if (n < 1000) return 1000;
  if (n > 60000) return 60000;
  return n;
}

export default function LoginPopups() {
  const [popups, setPopups] = useState(null);
  const [popupIndex, setPopupIndex] = useState(0);
  const [slideIndex, setSlideIndex] = useState(0);
  const pausedRef = useRef(false);
  const timerRef = useRef(null);

  useEffect(() => {
    api.getActivePopups().then(setPopups).catch(() => setPopups([]));
  }, []);

  const valid = popups && popups.length > 0 && popupIndex < popups.length;
  const popup = valid ? popups[popupIndex] : null;
  const slideCount = popup ? popup.slides.length : 0;

  useEffect(() => {
    if (!popup || slideCount <= 1 || pausedRef.current) return undefined;
    const ms = clampDurationMs(popup.slides[slideIndex] && popup.slides[slideIndex].duration_ms);
    timerRef.current = setTimeout(() => {
      setSlideIndex((i) => (i + 1) % slideCount);
    }, ms);
    return () => { if (timerRef.current) { clearTimeout(timerRef.current); timerRef.current = null; } };
  }, [slideIndex, slideCount, popupIndex]);

  if (!valid) return null;

  const slide = popup.slides[slideIndex];
  const isLastSlide = slideIndex === slideCount - 1;
  const isLastPopup = popupIndex === popups.length - 1;

  const clearTimer = () => { if (timerRef.current) { clearTimeout(timerRef.current); timerRef.current = null; } };

  const goNextPopup = () => {
    clearTimer();
    if (isLastPopup) {
      setPopups([]);
    } else {
      setPopupIndex((i) => i + 1);
      setSlideIndex(0);
    }
  };

  const next = () => {
    if (!isLastSlide) setSlideIndex((i) => i + 1);
    else goNextPopup();
  };

  return (
    <Modal open={true} onClose={goNextPopup}>
      <div
        style={{ textAlign: 'center' }}
        onMouseEnter={() => { pausedRef.current = true; clearTimer(); }}
        onMouseLeave={() => { pausedRef.current = false; setSlideIndex((i) => i); }}
      >
        {slide.image_url && (
          <img
            src={driveImageUrl(slide.image_url)}
            alt=""
            style={{ maxWidth: '100%', maxHeight: 320, borderRadius: 10, marginBottom: 15 }}
            onError={(e) => {
              const img = e.currentTarget;
              if (img.dataset.driveFallbackTried !== '1') {
                driveImgOnError(slide.image_url)(e);
                if (img.dataset.driveFallbackTried === '1') return;
              }
              img.style.display = 'none';
            }}
          />
        )}
        {slide.text && (
          <p style={{ fontSize: '0.95rem', whiteSpace: 'pre-wrap', marginBottom: 12 }}>{slide.text}</p>
        )}
        {slide.link_url && (
          <a
            href={slide.link_url}
            target="_blank"
            rel="noreferrer"
            style={{ display: 'inline-block', color: 'var(--primary-saffron)', fontWeight: 600, marginBottom: 15, textDecoration: 'underline' }}
          >
            {slide.link_text || slide.link_url}
          </a>
        )}

        {slideCount > 1 && (
          <div style={{ display: 'flex', justifyContent: 'center', gap: 6, margin: '10px 0' }}>
            {popup.slides.map((_, i) => (
              <span
                key={i}
                style={{
                  width: 8, height: 8, borderRadius: '50%',
                  background: i === slideIndex ? 'var(--primary-saffron)' : '#e5e7eb',
                }}
              />
            ))}
          </div>
        )}

        <div style={{ display: 'flex', gap: 10, justifyContent: 'center', marginTop: 15 }}>
          <button type="button" className="btn-submit" style={{ width: 'auto', background: '#e5e7eb', color: '#111' }} onClick={goNextPopup}>
            Skip
          </button>
          <button className="btn-submit" style={{ width: 'auto' }} onClick={next}>
            {isLastSlide ? (isLastPopup ? 'Done' : 'Next Announcement') : 'Next'}
          </button>
        </div>
      </div>
    </Modal>
  );
}

// mgmt/frontend-svelte/src/lib/components/LoginPopups.svelte
<script lang="ts">
  // Ported from React LoginPopups.jsx — after a fresh login, shows the active
  // popups (each with auto-advancing slides) in a modal, one popup at a time.
  import { api } from '$lib/api';
  import Modal from './Modal.svelte';
  import { driveImageUrl, driveImgOnError } from '$lib/driveUrl';

  const DEFAULT_DURATION_MS = 5000;
  function clampDurationMs(ms: unknown): number {
    const n = parseInt(ms as string, 10);
    if (!Number.isFinite(n) || n <= 0) return DEFAULT_DURATION_MS;
    if (n < 1000) return 1000;
    if (n > 60000) return 60000;
    return n;
  }

  let popups = $state<any[] | null>(null);
  let popupIndex = $state(0);
  let slideIndex = $state(0);
  let paused = false;
  let timer: ReturnType<typeof setTimeout> | null = null;

  $effect(() => {
    api.getActivePopups().then((p: any) => (popups = p)).catch(() => (popups = []));
  });

  let valid = $derived(!!(popups && popups.length > 0 && popupIndex < popups.length));
  let popup = $derived(valid ? popups![popupIndex] : null);
  let slideCount = $derived(popup ? popup.slides.length : 0);

  $effect(() => {
    void slideIndex;
    void slideCount;
    void popupIndex;
    if (!popup || slideCount <= 1 || paused) return;
    const ms = clampDurationMs(popup.slides[slideIndex] && popup.slides[slideIndex].duration_ms);
    timer = setTimeout(() => {
      slideIndex = (slideIndex + 1) % slideCount;
    }, ms);
    return () => {
      if (timer) { clearTimeout(timer); timer = null; }
    };
  });

  function clearTimer() {
    if (timer) { clearTimeout(timer); timer = null; }
  }

  let slide = $derived(valid ? popup.slides[slideIndex] : null);
  let isLastSlide = $derived(slideIndex === slideCount - 1);
  let isLastPopup = $derived(!!(popups && popupIndex === popups.length - 1));

  function goNextPopup() {
    clearTimer();
    if (isLastPopup) {
      popups = [];
    } else {
      popupIndex = popupIndex + 1;
      slideIndex = 0;
    }
  }

  function next() {
    if (!isLastSlide) slideIndex = slideIndex + 1;
    else goNextPopup();
  }
</script>

{#if valid && slide}
  <Modal open={true} onClose={goNextPopup}>
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div
      style="text-align:center;"
      onmouseenter={() => { paused = true; clearTimer(); }}
      onmouseleave={() => { paused = false; slideIndex = slideIndex; }}
    >
      {#if slide.image_url}
        <img
          src={driveImageUrl(slide.image_url)}
          alt=""
          style="max-width:100%; max-height:320px; border-radius:10px; margin-bottom:15px;"
          onerror={(e) => {
            const img = e.currentTarget as HTMLImageElement;
            if (img.dataset.driveFallbackTried !== '1') {
              driveImgOnError(slide.image_url)(e);
              if (img.dataset.driveFallbackTried === '1') return;
            }
            img.style.display = 'none';
          }}
        />
      {/if}
      {#if slide.text}
        <p style="font-size:0.95rem; white-space:pre-wrap; margin-bottom:12px;">{slide.text}</p>
      {/if}
      {#if slide.link_url}
        <a href={slide.link_url} target="_blank" rel="noreferrer" style="display:inline-block; color:var(--primary-saffron); font-weight:600; margin-bottom:15px; text-decoration:underline;">
          {slide.link_text || slide.link_url}
        </a>
      {/if}

      {#if slideCount > 1}
        <div style="display:flex; justify-content:center; gap:6px; margin:10px 0;">
          {#each popup.slides as _, i (i)}
            <span style="width:8px; height:8px; border-radius:50%; background:{i === slideIndex ? 'var(--primary-saffron)' : '#e5e7eb'};"></span>
          {/each}
        </div>
      {/if}

      <div style="display:flex; gap:10px; justify-content:center; margin-top:15px;">
        <button type="button" class="btn-submit" style="width:auto; background:#e5e7eb; color:#111;" onclick={goNextPopup}>
          Skip
        </button>
        <button class="btn-submit" style="width:auto;" onclick={next}>
          {isLastSlide ? (isLastPopup ? 'Done' : 'Next Announcement') : 'Next'}
        </button>
      </div>
    </div>
  </Modal>
{/if}
