// mgmt/frontend/src/components/VillageInput.jsx
import { useState, useEffect } from 'react';
import { useDropdownList } from '../useDropdownList.js';
import TransliterateInput from './TransliterateInput.jsx';

export default function VillageInput({ value, hiValue, onChange }) {
  const { options, hindiOf } = useDropdownList('Village');
  const villageNames = options.map(o => o['English Value']);
  const [customMode, setCustomMode] = useState(Boolean(value) && !villageNames.includes(value));

  useEffect(() => {
    if (value && villageNames.length && !villageNames.includes(value)) setCustomMode(true);
    else if (villageNames.includes(value)) setCustomMode(false);
  }, [value, options.length]);

  return (
    <>
      <select
        value={customMode ? 'Other' : (value || '')}
        onChange={e => {
          if (e.target.value === 'Other') {
            setCustomMode(true);
            onChange('', '');
          } else {
            setCustomMode(false);
            onChange(e.target.value, hindiOf(e.target.value));
          }
        }}
      >
        <option value="" disabled>-- Select Village --</option>
        {villageNames.map(v => <option key={v} value={v}>{v}</option>)}
        <option value="Other">Other</option>
      </select>
      {customMode && (
        <div style={{ marginTop: 8 }}>
          <TransliterateInput
            label="Village"
            placeholder="Enter village name"
            value={{ en: value || '', hi: hiValue || '' }}
            onChange={({ en, hi }) => onChange(en, hi)}
          />
        </div>
      )}
    </>
  );
}

// mgmt/frontend-svelte/src/lib/components/VillageInput.svelte
<script lang="ts">
  // Ported from React VillageInput.jsx — village dropdown (from the Village
  // dropdown list) with an "Other" custom-entry mode using TransliterateInput.
  import { createDropdownList } from '$lib/dropdownList';
  import TransliterateInput from './TransliterateInput.svelte';

  interface Props {
    value?: string;
    hiValue?: string;
    onChange: (en: string, hi?: string) => void;
  }
  let { value = '', hiValue = '', onChange }: Props = $props();

  const villageList = createDropdownList('Village');
  let villageNames = $state<string[]>([]);
  const unsub = villageList.subscribe((s) => (villageNames = s.options.map((o) => o['English Value'])));
  $effect(() => () => unsub());

  let customMode = $state(Boolean(value) && !villageList.current().some((o) => o['English Value'] === value));

  $effect(() => {
    if (value && villageNames.length && !villageNames.includes(value)) customMode = true;
    else if (villageNames.includes(value)) customMode = false;
  });
</script>

<select
  value={customMode ? 'Other' : value || ''}
  onchange={(e) => {
    const v = (e.currentTarget as HTMLSelectElement).value;
    if (v === 'Other') {
      customMode = true;
      onChange('', '');
    } else {
      customMode = false;
      onChange(v, villageList.hindiOf(v));
    }
  }}
>
  <option value="" disabled>-- Select Village --</option>
  {#each villageNames as v}
    <option value={v}>{v}</option>
  {/each}
  <option value="Other">Other</option>
</select>
{#if customMode}
  <div style="margin-top:8px;">
    <TransliterateInput
      label="Village"
      placeholder="Enter village name"
      value={{ en: value || '', hi: hiValue || '' }}
      onChange={({ en, hi }) => onChange(en, hi)}
    />
  </div>
{/if}
